### PR TITLE
Update mailer.js

### PR DESCRIPTION
**Pull request by mansikhemka**
#927 
I think this should work.

### CODE REVIEW

**Comment by Princu7** [comment]
@mansikhemka Thanks for the request. Could you squash your commits, please?

**Comment by Abhi2424shek** [comment]
@Princu7 use the squash and merge option!

**Comment by Princu7** [comment]
@Abhi2424shek Yes. That is a valid option. Although, squashing your own commits beforehand is a good practice in general.
@mariobehling @aayusharora Fix seems to be working fine.

**Comment by mariobehling** [comment]
Thank you!

**Comment by mansikhemka** [comment]
:)

**Pull request merged**
