### PR TITLE
Change navbar color and opacity

### PR DESCRIPTION
**Pull request by hoangvanthien**
Issue #864 

screen shot 2017-01-05 at 15 45 43

### CODE REVIEW

**Comment by aayusharora** [comment]
LGTM @hoangvanthien  Thanks :)

**Comment by mariobehling** [comment]
Sorry, but this is probably good for the mobile version, but not for the desktop version, where it changes the appearance of the site. The opacity is a feature of the desktop site, not a bug. Unfortunately I have to revert this as the desktop site does not fit the intended design outline anymore. It would be great, if you could make these changes for the mobile site only. Cheers.

**Comment by hoangvanthien** [comment]
@mariobehling The point is that this PR was included in my two tasks on GCI which were accepted. Does reverting affect my contribution in the contest?

**Comment by Princu7** [comment]
@hoangvanthien No, it shouldn't. You did it in good faith. But it would be infinitely better if you could help to make these changes for the mobile site only. Thanks!!

**Pull request merged**
