### PR TITLE
genetella integration

### PR DESCRIPTION
**Pull request by aayusharora**
@juslee  ,LIVE URL : http://geologist-patrick-65468.bitballoon.com/#/sessions

### CODE REVIEW

**Comment by aayusharora** [comment]
@juslee  , For now I am not running it with gulp, I have to rewrite gulp.js

**Comment by aayusharora** [comment]
@juslee , It will be better to have this  to be separate from master . Please don't merge it for now .
Have to remove many files

**Comment by juslee** [comment]
@aayusharora let me know when to merge. Looking decent.

**Comment by aayusharora** [comment]
@juslee , Before doing this , I think we have some change in plans .

**Comment by juslee** [comment]
is this ready to merge?

**Comment by aayusharora** [comment]
@juslee  ,Yes , But in a different branch like open-event-orga-server , we can merge it later with master .

**Comment by championswimmer** [comment]
You'll have to redo the PR then. Can you create branches @angularboy?
make gsoc2016/ui branch and PR to that

**Comment by aayusharora** [comment]
@juslee  , closing this Consider #211

**Pull request closed without merging**
