### PR TITLE
No matching results found dispaly in red

### LINKED ISSUE #1871: no result found in red
no result found should be displayed in red

**Would you like to work on the issue?**
yes

### PR DESCRIPTION
**Pull request by shubham3211**
Fixes #1871 
deployment link:- https://shubham3211.github.io/google/index.html

### CODE REVIEW

**Comment by shubham3211** [comment]
@agbilotia1998 done.

**Comment by agbilotia1998** [comment]
@shubham3211 can you please align this text with the input box, currently it is looking like this
screenshot-2018-5-23 f8-facebook developer conference 2017

**Comment by shubham3211** [comment]
@agbilotia1998 done :+1:

**Comment by agbilotia1998** [comment]
@shubham3211 is the preview link updated?

**Comment by shubham3211** [comment]
@agbilotia1998 done

**Pull request merged**
