### PR TITLE
Import Audio and Images Folder inside zip, Encode URL's of images

### PR DESCRIPTION
**Pull request by aayusharora**
- [x] Import Images in Zip by user
- [x] Import Audio in Zip by user.
- [x] Encode URL of images 
@championswimmer 

 Please check the cases before the merge though I have tested them.

1) Images and audio downloading from URL'S.
2) If they are provided in zip with folder names "images" and "audio" the app should work correctly.

### CODE REVIEW

**Comment by championswimmer** [comment]
@aayusharora I made a temp heroku app for this PR 
https://opev-webgen-dev-pr-521.herokuapp.com/live/preview/championswimmer@gmail.com/ots16orga/

Images are still not showing up after urlencoding

**Comment by championswimmer** [comment]
## hold this merge before #510 is done

**Comment by aayusharora** [comment]
@championswimmer 
1) Is the URL is correct in JSON.
2)Is it correctly downloaded and is present in image folder.

Can you please check these tests and give me an example where it is failing.

**Comment by championswimmer** [comment]
@aayusharora deferring these tests after I merge the src/generator nesting  ?

**Comment by championswimmer** [comment]
Setup a test deployment on https://opev-webgen-dev-pr-521.herokuapp.com/

**Comment by aayusharora** [comment]
@championswimmer  this testing require merge of PR https://github.com/fossasia/open-event-webapp/pull/521 If it looks good please merge.

**Pull request merged**
