### PR TITLE
Implemented png dowload for schedule page

### PR DESCRIPTION
**Pull request by Lplenka**
Fixes #[1252]

Changes: 
1- Download as PNG button for the Calendar view of schedule.
2- Download as PNG button for the List view of schedule.
3- Downloads are PNG images named as per date of the event.

Sample Webpage:
Before Changes:
[https://demolp.github.io/FOSSASIA_Summit/schedule.html](https://demolp.github.io/FOSSASIA_Summit/schedule.html)

After Changes:
[https://demolp.github.io/FOSSASIA%20Summitnew/schedule.html](https://demolp.github.io/FOSSASIA%20Summitnew/schedule.html)

### CODE REVIEW

**Comment by Princu7** [comment]
@lplenka Marvellous work. :clap: Thanks!!. Please see to the requests made by the @geekyd. Just one slight issue is that the full width of the schedule is not being captured. There were similar problems which occurred in the orga-server too. Please see the recent commits and the file changed. Hope, we can fix it. Thanks.

https://github.com/fossasia/open-event-orga-server/commit/a5bc949949d14d46764feb9f2d5b7ea4beed045e
https://github.com/fossasia/open-event-orga-server/commit/4e191c433a2b9747bcc7e824a91f8ee9d9347081

**Comment by Lplenka** [comment]
@Princu7 Thanks, I am working on that.
@geekyd Thanks for pointing the issue, I also missed that :sweat_smile:

**Comment by Lplenka** [comment]
@geekyd @Princu7 I solved the issue with rendered Calendar view.
Now full width is displayed.

You guys can check here:
https://demolp.github.io/FOSSASIA%20Summitnew/schedule.html

But I am facing a problem with gulp file, seems it is not concatenating 'FileSaver.js' file properly.
I am getting this error after generating the webpage.

error

I just added FileSaver.js & html2canvas.js  to `gulpfile.js`

``` javascript
 gulp.task('scheduleJs', function() {
    return gulp.src([dir + 'FileSaver.js', dir + 'social.js', dir + 'scroll.js', dir + 'navbar.js', dir + 'calendar.js', dir + 'popover.js', dir + 'html2canvas.js',  dir + 'jquery.lazyload.js'])
    .pipe(iife({ useStrict : false}))
    .pipe(concat('schedule.min.js'))
    .pipe(babel({ presets: ['es2015'] }))
    .pipe(uglify().on('error', function(e) {
        console.log("Error while compiling schedule.js");
    }))
    .pipe(gulp.dest(path + '/js/'));
  });
```


Any suggestions?

**Comment by Princu7** [comment]
@Lplenka Just add window.saveAs = saveAs at the end of the FileSaver.js file and it should be fine. Thanks!!

**Comment by Lplenka** [comment]
@Princu7 Thanks! That worked.
PR is ready for review.

You guys can check here:
https://demolp.github.io/FOSSASIA%20Summitnew/schedule.html

**Comment by Princu7** [comment]
At first, I thought there was some problems with the order in which the files were being concatenated and minified but after playing with their order, the `Reference Error` didn't seem to go away. It threw a Reference error saying that `saveAs` is not defined.

Then after some time, it hit me that in the gulp, we concat and minify the js files. This can lead to variables and function name collision so we wrap each of the script files inside a function. In other words, we make an `IIFE` (Immediately Invoked Functional Expressions) for each of the script files. `IIFE` have the property that they are executed immediately after the function is created. The variables in `Javascript` (declared with var) have a function level scope so the namespace is not polluted since each of the script files is wrapped up inside its own IIFE with all its variables and event listeners inside it. The global namespace is not polluted.

I went through the code of the FileSaver.js library. It was declaring a variable `saveAs` which was actually the function for saving the images. Now, since that file is wrapped up inside IIFE after passing through the gulp, the variable `saveAs` is isolated from the global namespace and other scripts. That's why when we call the `saveAs` from the other script, a `Reference Error` is thrown away because it does not exist globally and hence can't be called from the other scripts. So, to solve it, we just explicitly attach the saveAs variable to global window object by adding `window.saveAs = saveAs` at the end of the FileSaver.js file. Now, we can call `saveAs` from any of the scripts. Hope that clears it up a bit. Thanks!!

**Comment by geekyd** [comment]
@Princu7 Great explanation. 
@Lplenka Great work! Just one more thing the columns in calendar view have gaps between them. Can you please check why it is happening?

screenshot from 2017-05-27 00-00-25

**Comment by Lplenka** [comment]
@geekyd The png captures the total HTML, there are gaps in the HTML itself, and hence in the captured pic. Not related to the code I am sure.

**Comment by geekyd** [comment]
@Lplenka The attached screenshot was of the HTML not the PNG. Please check https://fossasia.github.io/open-event-webapp/schedule.html the issue did not exist in the previous version. Thanks!

**Comment by Lplenka** [comment]
@geekyd Okay sure, I will cross check.

**Comment by Lplenka** [comment]
@geekyd Seems there was just a problem in that rendered website.
I generated again and deployed.

Have a look:
https://demolp.github.io/FOSSASIA%20Summitnew/schedule.html

**Comment by geekyd** [comment]
@Lplenka It is rendering correctly now, Great work! Can you please remove the extra width of the png, there is empty area on the right?

**Comment by Lplenka** [comment]
@geekyd  done!

**Comment by Princu7** [comment]
@Lplenka Excellent. Functionality wise everything looks perfect now. Sorry for bothering again but can you please reduce the no of commits from 5 to maybe 2, please? One commit can be for adding the additional files and the second commit can be for implementing png download of the schedule. Also, in the `schedule.hbs` file, some of the lines are not correctly indented. The standard is 2 spaces for indentation. I know that in many areas of that file, it is not being followed but would be great if you could correct it in this PR. I will open a subsequent issue soon for fixing indentation problems. Thank you so much!!

**Comment by Princu7** [comment]
Commits look good and pertain to a specific task. So, squashing is not really required here.

**Comment by Lplenka** [comment]
@Princu7 Thanks!

**Comment by geekyd** [comment]
@Lplenka Great work! Can you please have a look at why codacy is failing? Check https://www.codacy.com/app/mb/open-event-webapp/pullRequest?prid=672970 and please fix the issues. Thanks!

**Comment by Lplenka** [comment]
@princu7 I agree, this codacy error is due to the library (FileSaver.js).  No point finding lint errors in libraries. 
I checked it earlier, would have fixed if there would have been any error in our code.

**Comment by geekyd** [comment]
@Princu7 Thanks for explaining. We will take care of it in separate issue. Merging This!
@Lplenka Great work! :)

**Comment by Lplenka** [comment]
Thanks! @geekyd  and  @Princu7

**Pull request merged**
