### PR TITLE
Add favicon.ico for #1495

### LINKED ISSUE #1495: Add favicon to event overview page
**Actual Behaviour**

Favicon is missing for https://sched.eventyay.com/

**Expected Behaviour**
Add favicon to https://sched.eventyay.com/. Reference file : https://github.com/fossasia/open-event-webapp/blob/development/src/backend/overviewSite/index.html

### PR DESCRIPTION
**Pull request by cbelisle**
Fixes #1495 

I just copied the favicon.ico from the src/www folder, without adding a reference in index.html since the browser should detect it automatically. I hope it's ok!

### CODE REVIEW

**Comment by agbilotia1998** [comment]
@cbelisle thanks for this PR.Please provide a demo link or screen shot to review this PR.

**Comment by lapmid** [comment]
what changes i have to do please tell

**Comment by cbelisle** [comment]
I added a reference in the html file. Here is the screenshot in firefox:

image

**Comment by geekyd** [comment]
@cbelisle Thanks it looks good. Can you please squash the commits?

**Comment by cbelisle** [comment]
Squashed the two commits into "Add favicon.ico"

**Comment by agbilotia1998** [comment]
@cbelisle please update your branch and squash the commits.

**Comment by cbelisle** [comment]
Sorry, first time squashing commits. It should be ok now.

**Comment by agbilotia1998** [comment]
@cbelisle no problem there , now it is perfectly fine.Thanks for this PR :+1:

**Pull request merged**
