### PR TITLE
Fixes #977: adds scroll to top button

### LINKED ISSUE #977: Add a minimalistic scroll to top sticky button on tracks page
When the the number of tracks and sessions is on the higher side , for instance on the fossasia'16 site generated with webapp, it becomes cumbersome to reach the top. If a user is in the midst of the page vertically, the only option is to scroll all the way to bottom and click 'back to top' link or manually scroll to the  top of the page. It can be avoided by implementing a very minimalistic scroll to top button which appears on the bottom right of the screen as soon as the user starts scrolling.
I can show the proposed UI, if it seems a valid issue.

### PR DESCRIPTION
**Pull request by CosmicCoder96**
It adds a minimalistic scroll to top button which appears only if the user starts scrolling.
Here is a preview: 
image

and here is a screenshot on mobile interfaces

image

Live preview is available at : 
https://cosmiccoder96.github.io/open-event-webapp/tracks.html

@aayusharora @Princu7 Please review

### CODE REVIEW

**Comment by Princu7** [comment]
@CosmicCoder96 Looks great. It would be great if you could increase the speed up a bit. It's seem a little slow when compared to the speed which we get on clicking the dates.

**Comment by geekyd** [comment]
@CosmicCoder96 Great work!
I agree with @Princu7 it seems a little slow. Increasing the speed would be great.

**Comment by CosmicCoder96** [comment]
@princu7 @geekyd  Thanks ! Have increased the scroll speed.

**Comment by aayusharora** [comment]
@CosmicCoder96 Please squash the commits. Thanks !!

**Comment by CosmicCoder96** [comment]
@aayusharora Thanks.I have squashed the commits.

**Comment by CosmicCoder96** [comment]
@aayusharora I have squashed the commits.

**Comment by Princu7** [comment]
@CosmicCoder96 Thanks.

**Pull request merged**
