### PR TITLE
Fixes the zip upload problem

### LINKED ISSUE #952: UX: Stop website generation when zip is cancelled
The website generation does not stop even if the zip gets cancelled in between the generation process.

**Steps to reproduce the situation**

1. Upload the zip and hit generate app
2. Cancel the zip before the generation of the app is completed.

ezgif com-gif-maker 1

### PR DESCRIPTION
**Pull request by Princu7**
Fixes #952

**Changes**:
* The zip file continued to upload to server even after pressing the cancel button leading to wastage of bandwidth and inability to upload a new zip file until the first file finished uploading.

* It was due to internal implementation of `socket-io-file-upload` library. Made some changes and now using the `socket-io-stream` library.

* Test Server : http://secure-meadow-20680.herokuapp.com/

**Demonstration for the changes**: 
I created a video demo to demonstrate the changes
https://www.useloom.com/share/805184de385c45c3b2d7adfda48d8615
Excuse my slow internet connection :)

### CODE REVIEW

**Comment by geekyd** [comment]
@Princu7  Looks great. The socket-io-stream library is working really as expected. :)

**Comment by aayusharora** [comment]
@Princu7 Can you please remove the conflicts?

**Comment by Princu7** [comment]
@aayusharora I have removed the conflicts. Please review it. Thanks!!

**Comment by aayusharora** [comment]
Thanks for removing the conflicts :+1:

**Pull request merged**
