### PR TITLE
use day-wise navbar only in tracks page

### PR DESCRIPTION
**Pull request by championswimmer**
Signed-off-by: Arnav Gupta <championswimmer@gmail.com>

### CODE REVIEW

**Comment by championswimmer** [comment]
As is evident in the screenshots, 
it makes sense to have the day wise drop downs only on track page. They make no sense to have them on the rooms or speakers page
(the dropdowns work only for anchor tags inside tracks page) 

screenshot from 2016-08-06 02-17-03
screenshot from 2016-08-06 02-17-11
screenshot from 2016-08-06 02-17-19

**Comment by championswimmer** [comment]
@mariobehling @aayusharora 
Please share your views on this before merging it

I have not fully tested out all kinds of responsive issues yet. If this makes sense, then i'll test it out thoroughly and update PR if needed with fixes

**Comment by mariobehling** [comment]
@championswimmer Do you have a test site to try this out?

**Comment by mariobehling** [comment]
Ok, I think we can just follow sched.org. Simply add the dates on the top of the pages like that

screenshot from 2016-08-05 23 22 39

1. Schedule (we dont have it yet)
2. Track
3. Rooms

**Comment by championswimmer** [comment]
@mariobehling here is live example

http://championswimmer.in/open-event-webapp/tracks.html

Ok, will do as you suggest as per sched.org

**Comment by mariobehling** [comment]
Hey, what is the status? Let's get to a working version. This should be quick to implement.

**Comment by championswimmer** [comment]
@mariobehling This cannot be done like this 

screenshot from 2016-08-05 23 22 39

Because, each day has a dropdown containing tracks for that day. See this - 
screenshot from 2016-08-11 00-20-38

**Comment by mariobehling** [comment]
Go step by step and get rid of the dropdown. The UI needs to be simplified.

**Comment by championswimmer** [comment]
done via this https://github.com/fossasia/open-event-webapp/pull/613

so closing

**Pull request closed without merging**
