### PR TITLE
fixed title in tracks page

### PR DESCRIPTION
**Pull request by geekyd**
This PR contains the fix to #940

### CODE REVIEW

**Comment by Princu7** [comment]
@geekyd Thanks for the request. Code looks good to me. But it would be really great if you could add a live link to the gh-pages of the event website. We could test it more thoroughly then. Thanks!!

**Comment by geekyd** [comment]
@Princu7 sure can you please guide me about how to add link to gh-pages?

**Comment by shubham-padia** [comment]
@geekyd LGTM. To setup gh pages, first follow the instruction at pages.github.com. Then visit travis-ci.org and setup a variable `GH_TOKEN` equal to the api token you get at https://github.com/settings/tokens. And you'll be good to go

**Comment by aayusharora** [comment]
Thanks @geekyd @shubham-padia :)

**Pull request merged**
