### PR TITLE
Adds video stream support to v1 web apps

### PR DESCRIPTION
**Pull request by agbilotia1998**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.

#### Short description of what this resolves:
Adds video stream feature for sessions in v1 web apps and also incorporates slides data on rooms page.

Fixes: #1892 #1914 
Preview Link: https://agbilotia1998.github.io/Fossasia2018

### CODE REVIEW

**Comment by agbilotia1998** [comment]
@geekyd @aayusharora please review.

**Comment by agbilotia1998** [comment]
@geekyd please review.

**Comment by geekyd** [comment]
@agbilotia1998 Can you look into the codacy issues?

**Comment by agbilotia1998** [comment]
@geekyd done!! please review.

**Comment by agbilotia1998** [comment]
@geekyd @shubham3211 please review!! The remaining codacy issues are related to their pattern matching technique I guess, please check once.

**Comment by agbilotia1998** [comment]
@ParthS007 @pradeepgangwar @mayank8318 please review: https://agbilotia1998.github.io/Fossasia2018/index.html 
Screenshot:
screenshot-2018-6-10 fossasia summit

**Pull request merged**
