### PR TITLE
Optimises background image and reduces the size

### LINKED ISSUE #1122: Background image as png and too large
The header background image of start page is saved as a png and very large, e.g. the image of the FOSSASIA Summit is 1.8MB.

### PR DESCRIPTION
**Pull request by geekyd**
Fixes #1122

- Converts background image to jpg
- Reduces the size of the image by 8x.
- Size is down to 226kb from 1.8mb

Test server :
https://open-event-web-appp.herokuapp.com/

Demo pages :
https://geekyd.github.io/eventApplication/

@mariobehling @aayusharora @Princu7 Please review. Thanks

### CODE REVIEW

**Comment by Princu7** [comment]
@geekyd Looks good to me. Some points

* Why is there need for both `urls.background_path` and `urls.background_url`?  They are almost identical minus the type of extension at the end. Same for` background_path` and `background_url` which are identical.

* Remove the `console.log(image)` line. No need for that.

**Comment by geekyd** [comment]
@Princu7` urls.background_url` hold the jpg path used in the handlebars `urls.background_path` is used to store the path of the downloaded file, and is used to convert the file. 

I will remove the console.log

**Comment by Princu7** [comment]
@geekyd Okay. Nice.

**Comment by Princu7** [comment]
Thanks!!

**Pull request merged**
