### PR TITLE
right navigation bar made proper.

### PR DESCRIPTION
**Pull request by SilentFlame**
The left navigation bar made consistent throughout the pages `session, speakers, tracks`.
@mariobehling , @jig08 
have a review if works as expected, then can merge and close Issue.

### CODE REVIEW

**Comment by SilentFlame** [comment]
also resolves #132. 
can close Issue if you you think  this does the whole work. :smile:

**Comment by SilentFlame** [comment]
I guess #116 is also resolved via this PR.  @SaptakS @daminisatya  have a look.

**Comment by aayusharora** [comment]
@SilentFlame ,please remove the conflicts.

**Comment by SilentFlame** [comment]
@aayusharora 
Initially they weren't present. so let me check again.

**Comment by championswimmer** [comment]
rebase if it is to be merged.

**Comment by championswimmer** [comment]
make new pr on new refactored source

**Comment by SilentFlame** [comment]
@championswimmer 
sorry I bymistake deleted the branch, I guess that was the reason.
will come up with new PR with latest refactored code.

**Pull request closed without merging**
