### PR TITLE
Issue718

### PR DESCRIPTION
**Pull request by jainaman224**
@mariobehling Please review at https://jainaman224.github.io/open-event-webapp/issue718/tracks.html regarding #718 .
Thank you.

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you. Looks good, but why do the times not match anymore, e.g. Grand Opening starts at 15.30.

**Comment by jainaman224** [comment]
@mariobehling Sir, I think time is correct because time for Grand Opening is 9:30 UTC and time zone for my country is UTC+5:30.

**Comment by mariobehling** [comment]
@jainaman224 Yes, I understand your idea, but the timezone of a real-world event should be the local timezone where the event takes place. Please also resolve merge conflicts. Thank you!

**Comment by jainaman224** [comment]
@mariobehling It will be better to get local time rather than UTC time in json itself. It will be faster.

**Comment by mariobehling** [comment]
Thanks for your ideas, but we had this discussion before and for now the current implementation works best across projects. Cheers

**Comment by mariobehling** [comment]
@jainaman224 Let's progress. I am merging this and we continue from there. Thank you.

**Comment by jainaman224** [comment]
@mariobehling Thank you.

**Pull request merged**
