### PR TITLE
Added Event page 

### PR DESCRIPTION
**Pull request by aayusharora**
- [x] Compile Event page and make that available in Zip.
- [x] Write Markup and styling for Event page
- [x] Async load image at top
- [x] Add event Name, Place , Time and date on top of image same as orga.
- [x] Add speaker section
@championswimmer @mariobehling I will carry out more changes in next PR. Please check and merge this.

### CODE REVIEW

**Comment by aayusharora** [comment]
@championswimmer Merge this I will carry out More UI/UX in next PR 
Image in Header 


Speakers Section

**Comment by championswimmer** [comment]
@mariobehling should we show all speakers on front page ?

**Comment by aayusharora** [comment]
@championswimmer I have made this because I think orga UI follows the same

**Comment by mariobehling** [comment]
Thanks. The transparency is too dark. It is also to dark on the orga server.

**Pull request merged**
