### PR TITLE
#1260: added side navigation menu in mobile view

### LINKED ISSUE #1260: Mobile View: Move in (slide on top) menu from right instead from top down
In mobile view, please change the menu dropdown to be a slide on top menu moving in from the ride side. Occupy the whole height of the screen.

screenshot from 2017-05-01 15-53-16

Ensure to slide "on top" from the right side of the screen. This way we make it more similar to our Android app. A sidebar is also more similar to FOSSASIA website.
screenshot from 2017-05-01 15-54-31

### PR DESCRIPTION
**Pull request by anu-007**
Fixes #1260

Changes: [Added slide from side navigation menu in mobile view]

Screenshots for the change: 
sidenav with animation approx 60fps
alt text

Demo: https://afternoon-woodland-82522.herokuapp.com/

### CODE REVIEW

**Comment by mariobehling** [comment]
Please share a link to an actual test site.

**Comment by anu-007** [comment]
test site : ( https://anu-007.github.io/event-webapp/ )

**Comment by aayusharora** [comment]
@anu-007 The image is not full-width in desktop view

**Comment by mariobehling** [comment]
Please see the following issues

* Changed the top background image for no reason
* Sidebar should cover top to down completely (compare fossasia.org)
* There is a gray border on the left of sidebar for no reason
* Social links are not aligned to the left

screenshot from 2017-05-09 06-44-41

**Comment by anu-007** [comment]
@mariobehling @aayusharora I made some changes as requested please review.
demo- https://anu-007.github.io/event-webapp/

**Comment by Princu7** [comment]
@anu007 Had a quick look at the code. It seems like, you are using two data targets element `side-collapse` and `side-collapse-container` due to which the whole page is moved instead of only the side area being moved. What we can do here is that we don't collapse the header and the body. We show the side menu on top of the other contents and make it visible by using the `z-index` property and changing the `background color`  of side container.

**Comment by anu-007** [comment]
@Princu7 I misunderstood the issue, I thought the side nave is designed so that it moves the body to the left like that of fossasia.org, I will correct it as soon as possible.Thanks.

**Comment by Princu7** [comment]
@anu-007 Ok. Great. No problem :smile:

**Comment by Princu7** [comment]
@anu-007 Please update on this PR. Thanks!!

**Comment by anu-007** [comment]
@Princu7 currently my end semester exams are going on and I hardly getting any time to work on this, if this PR is causing a delay in the development process you can take this up. I am very sorry for this inconvenience.Thanks !!

**Comment by mariobehling** [comment]
Closing due to inactivity.

**Pull request closed without merging**
