### PR TITLE
Speakers Page Added

### PR DESCRIPTION
**Pull request by aayusharora**
Issue Related #371
@mariobehling @championswimmer Check and Merge PLease

### CODE REVIEW

**Comment by championswimmer** [comment]
add speaker bio under their org and position as well ?

**Comment by aayusharora** [comment]
@championswimmer I will add it next PR, please see the gitter chat once.

**Comment by mariobehling** [comment]
Ok, good. Please fix the houndci issues. We can then decide if we want to go the way of the FOSSASIA pages to show more info on scroll over or below the speakers.

**Comment by aayusharora** [comment]
@mariobehling  Thanks doing it right now.

**Pull request merged**
