### PR TITLE
Added sister projects

### PR DESCRIPTION
**Pull request by samyakbvs**
Collaborated with @saarthakchats

We had to collaborate on this small improvement as Saarthak didn't have the resources to clone and squash his commits
PSlab - Samyak

### CODE REVIEW

**Comment by saarthakchats** [comment]
Yes, I had added badgeyay to @samyakbvs repo, my commit is not visible as the commits were squashed by Samyak. I confirm that I have worked on this PR.
Fixes #1654

**Comment by geekyd** [comment]
@saarthakchats There is only one commit in the PR. Either do not squash the commit or send separate PRs. Thanks

**Comment by geekyd** [comment]
@samyakbvs @saarthakchats Please share deployment link.

**Comment by geekyd** [comment]
@saarthakchats You should open PR of yours. Check message on the thread of your task.

**Comment by saarthakchats** [comment]
@geekyd ok

**Comment by saarthakchats** [comment]
@geekyd 
But first you'll have to merge this #1650

**Comment by samyakbvs** [comment]
COnflicts have been resolved please merge

**Comment by samyakbvs** [comment]
@isuruAb

**Comment by saarthakchats** [comment]
I cant squash

**Comment by harshit98** [comment]
@samyakbvs Would be better to open this as separate PR instead of collaboration.

**Pull request closed without merging**
