### PR TITLE
index.html: Susper in quick menu

### PR DESCRIPTION
**Pull request by stellargo**
Susper link is added to the quick menu tab.

Fixes https://github.com/fossasia/open-event-webapp/issues/1505

Changes: Susper is added to the quick links menu.

Screenshots for the change: 
screen shot 2017-10-19 at 1 54 42 pm

### CODE REVIEW

**Comment by stellargo** [comment]
@mariobehling all icons are weighted downwards as shown in screenshot so I followed the trend. Should I have a seperate PR to adjust all of them then to maintain symmetry?

**Comment by mariobehling** [comment]
Please follow susper.com

**Comment by stellargo** [comment]
@mariobehling It really would help a lot if you could give a little more info as to what you want compared. I am assuming that you want all images to be a little more to the centre instead of bottom. If I change the positions of all icons I would really be doing injustice to the name of the issue, i could make a seperate issue to solve that.

**Comment by ParthS007** [comment]
@stellargo Please close this PR  as this issue is already resolved in #1531

**Comment by geekyd** [comment]
Closing this PR as this issue has been resolved please take up some other issue. :)

**Pull request closed without merging**
