### PR TITLE
Features PDF: Export schedule as pdf

### LINKED ISSUE #1252: Implement pdf download of schedule, especially the calendar view
Implement a pdf download of the schedule similar to the orga server.

### PR DESCRIPTION
**Pull request by harsh-98**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

Use jsPdf lib for exporting the schedule as pdf. The pdf can comprise of multiple pages so that the whole schedule can be converted into pdf. 

Fixes #1252

### CODE REVIEW

**Comment by harsh-98** [comment]
@agbilotia1998  https://drive.google.com/open?id=1IW8GEaIn5RATd5yVWjLxIhESglGyOQMU the export pdf is here

**Comment by geekyd** [comment]
@harsh-98 Please deploy thee generated app on gh-pages to make the process of reviewing the PR faster. Thanks

**Comment by harsh-98** [comment]
@geekyd I am having problem hosting webapp on heroku since for redis credit card verification is required.  And the app is working perfectly, I have also attached the link of the pdf generated so that u can view and verify. Is there some other platform on which I can host it?

**Comment by harsh-98** [comment]
@geekyd And the app is working perfectly, I have also attached the link of the pdf generated so that u can view and verify. https://drive.google.com/open?id=1IW8GEaIn5RATd5yVWjLxIhESglGyOQMU the export pdf is here

**Comment by harsh-98** [comment]
@geekyd whole schedule can also be downloaded.

**Pull request merged**
