### PR TITLE
Fixed #1615:Improved documentation

### LINKED ISSUE #1615: Heroku deployment
The image in the Heroku deployment doc is outdated

### PR DESCRIPTION
**Pull request by samyakbvs**

### CODE REVIEW

**Comment by samyakbvs** [comment]
Simplistic change

**Comment by ParthS007** [comment]
@samyakbvs Please close this PR and make it after #1611 is merged 👍

**Comment by samyakbvs** [comment]
Instead of closing, I am updating will that be okay?

**Comment by geekyd** [comment]
@samyakbvs Please open an issue before sending a PR. Also update the screenshot of the webapp.

**Comment by samyakbvs** [comment]
Yes doing it

**Comment by samyakbvs** [comment]
Pls merge thanks!

**Comment by samyakbvs** [comment]
Squashing the commits...

**Comment by samyakbvs** [comment]
This the limit to which I can squash, I am sorry pls merge

**Comment by mariobehling** [comment]
This PR is lacking an issue and description. Please help the review team and follow best practices. Hope you can make a new PR doing so. Closing it therefore. Thank you.

**Comment by samyakbvs** [comment]
Okay making another

**Pull request closed without merging**
