### PR TITLE
Frontend-issues

### PR DESCRIPTION
**Pull request by aayusharora**
Issue related #516 
- [x] images are not shown (no need for explanation, rather open an issue and outline a solution)
  Issue https://github.com/fossasia/open-event-orga-server/issues/1877#issuecomment-235212941 will   be adding a placeholder for null images.
- [x] Check all links, e.g. home screen not linking to defined home
- [ ] Rethink usability, why are there different font sizes in dropdown menu?
- [x]  Pages in small resolution are not using full width and breaking style sometimes
- [x] No X-axis scroll bar #518 Parent issue #515
- [x]  Scrollbar removed from Pop-over

    Change in UX    
1. Inline sessions to utilize white space.
2. Full width container to contain the elements.

### CODE REVIEW

**Comment by aayusharora** [comment]
@mariobehling about the comment
**Rethink usability, why are there different font sizes in dropdown menu?**
Can you please elaborate with a snapshot. I am feeling difficult to find it exactly.

**Comment by mariobehling** [comment]
No, problem. Do first what you can and we follow up step by step.

**Comment by championswimmer** [comment]
@mariobehling @aayusharora can we merge this first ? right now there are UI fixes

The **rethink usability** topic is open ended, we can do that in a future PR. We can discuss that more in a separate issue too if we want

**Comment by aayusharora** [comment]
Yes @championswimmer It's already cover lot of fixes, kindly merge.

**Pull request merged**
