### PR TITLE
added the icon at the title bar

### PR DESCRIPTION
**Pull request by rohythakur**
i have added the icon at the title bar of the website as per instructions as given previously and instructions at https://codein.withgoogle.com/dashboard/task-instances/6222480846880768/?sp-page=1

### CODE REVIEW

**Comment by rohythakur** [comment]
@mananwason  I have deleted that and created a new pull request

**Comment by mananwason** [comment]
@rohythakur I think you forgot to comment the other commit messages while rebasing. Please fix that using edit mode of rebase.
screen shot 2015-12-27 at 1 07 50 pm

**Comment by mananwason** [comment]
Also you can rebase in the same PR. You don't have to create a new PR for every change. Cheers!

**Comment by rohythakur** [comment]
@mananwason  ok I got it , but I don't understand what are you trying to say by other commit messages

**Comment by rohythakur** [comment]
@mananwason  I have updated the comment using that , anything else I can do

**Comment by mananwason** [comment]
@rohythakur It's still there. This means that squashed two commits and the commit that resulted had the commit message of both the previous commits. Please check again.

**Comment by rohythakur** [comment]
@mananwason  sorry for this but I haven't squashed the commits I have deleted the previous commit and then created a new pull request  ,and I have closed the previous pull request

**Comment by rohythakur** [comment]
@mananwason  sorry for this ,but I have also updated the comment

**Comment by mananwason** [comment]
@rohythakur Please rebase and edit commit message. You can refer to this https://help.github.com/articles/changing-a-commit-message/

**Comment by rohythakur** [comment]
@mananwason  sorry , I am a beginner that's why all of this happened , I think now I have changed the commit message , if not tell me

**Comment by rohythakur** [comment]
@mananwason  and thanks for all what have you done

**Comment by mananwason** [comment]
@rohythakur It's still there. If you click the dots next to commit message, you'll see so.You need to comment the unnecessary commit messages by adding a `#` in front of them.

**Comment by rohythakur** [comment]
@mananwason   I have removed that , can you  please check it now

**Comment by mananwason** [comment]
Nice work @rohythakur. I'll approve your task now :smile:

**Comment by rohythakur** [comment]
@mananwason  thanks for all, from next time  I will take care of it , I have learned lot

**Comment by mananwason** [comment]
@rohythakur That was the goal. Through GCI we want to make you ready for open source contribution.

**Pull request closed without merging**
