### PR TITLE
Merge Development into Master

### PR DESCRIPTION
**Pull request by Princu7**
Merges changes in the development branch into master. 
Test Server is here
https://young-woodland-76564.herokuapp.com/
@aayusharora @mariobehling Please check and review. Thanks!!

### CODE REVIEW

**Comment by aayusharora** [comment]
@princu There seems a lot of conflicts while checking this on local . Can you recheck on local with development merging master. We need to resolve those conflicts so that the development branch changes remain intact :)

**Comment by aayusharora** [comment]
@Princu7 Have you removed the Conflicts on local ?
Can you please explain the procedure, this can results in bad things if not handled properly.

**Comment by Princu7** [comment]
@aayusharora Yes, I removed all the conflicts locally. First I checked out the master branch of this repository into my local repository. ` Upstream` is the remote of this repository.

`git checkout -t -b master upstream/master`

This created a master branch in my local repo with the contents of master branch of this repository. Then I just ran the command

`git merge --squash upstream/development`

There were a lot of different types of conflicts(content conflict, modify/delete conflict, delete/modify conflict). I resolved them all and then created the request to the master branch. :sweat_smile: 

All the unit tests seem to pass and there seem to be no merge conflicts in this pull request. I also deployed a test server on Heroku which I made of my master branch itself. Please guide if something is incorrectly done. Thanks.

**Comment by aayusharora** [comment]
OK Looks good !! Merging this :)

**Pull request merged**
