### PR TITLE
Cache variables in form.js

### PR DESCRIPTION
**Pull request by aakash-cr7**
Caching variables in the file form.js.

### CODE REVIEW

**Comment by championswimmer** [comment]
@aakash-cr7 we are not really using form.js right now (it's doing pure HTML5 form POST). 

before this, if you want to, you can help fixing the AJAX request. The current code does not work (the backend does not receive the file) .

**Comment by aakash-cr7** [comment]
@championswimmer Great! I'll look into the AJAX request part and let you know if I have any issues.

**Comment by aakash-cr7** [comment]
@championswimmer in `main.js` file, we are adding a `click` event to a button with id `#btn`, but there exists no such button?

**Comment by championswimmer** [comment]
@aakash-cr7 form.js has significantly changed in development branch. this is not needed anymore. 
Please continue to contribute to development branch, your contributions have been really helpful

**Pull request closed without merging**
