### PR TITLE
make the search box UI better

### PR DESCRIPTION
**Pull request by championswimmer**
was using default browser UI, looked ugly. 
using bootstrap form-control css now

### CODE REVIEW

**Comment by championswimmer** [comment]
Before
screen shot 2016-10-06 at 5 47 36 am

After
screen shot 2016-10-06 at 5 47 25 am

**Comment by mariobehling** [comment]
Thank you. Please make a pull request for the same style for all pages.

Please stay with gray colors instead of blue to keep the web app colors. Cheers.

**Comment by mariobehling** [comment]
Could you also link this to an issue, please?

**Comment by championswimmer** [comment]
Sure, making issue and making changes on all pages

**Comment by mariobehling** [comment]
@championswimmer Thank you. Looking forward to the update.

**Comment by mariobehling** [comment]
Closing due to inactivity.

**Pull request closed without merging**
