### PR TITLE
Changes behavior of day buttons in tracks & rooms

### LINKED ISSUE #1259: Change behavior of gray day buttons and related changes on tracks and rooms page
This is a follow up to earlier discussions about the date buttons on the different pages. There are two kinds of buttons for dates on the pages. The question is: How can the functionality of these two buttons be united. The idea of this issue is: The dark gray buttons should act in a way like the date buttons in the calendar view. 

The desired functionality is: 

* On click 
  * a) expand to show tracks or rooms and 
  * b) show event data of specific date (similar to behavior of date buttons in calendar view).

screenshot from 2017-05-01 14-08-27
_In the screenshot, if the user clicks "18th May" the information below should be showing 18th May instead of 17th May._

* Secondly as the top date buttons are not required anymore, please take them out.

* Thirdly: Change the look and position of the buttons on the "Schedule" page to match the other pages.

### PR DESCRIPTION
**Pull request by geekyd**
Fixes #1259 

Changes: Changes behaviour of day buttons in tracks and rooms page. Removes top day buttons. 
Aligns date in calendar view to make it consistent with list view.

Screenshots for the change: 
screen shot 2017-05-03 at 5 58 55 am
screen shot 2017-05-03 at 5 59 18 am

Demo link: https://geekyd.github.io/eventApplication

@mariobehling @aayusharora @Princu7 Please review. Thanks

### CODE REVIEW

**Comment by geekyd** [comment]
@mariobehling Do you mean changing the button style on schedule page to the style of day buttons on tracks and rooms page?

The "Starred" button can be aligned next to the search button I think that will be a good place to place it.

**Comment by mariobehling** [comment]
> Do you mean changing the button style on schedule page to the style of day buttons on tracks and rooms page?

Yes, correct.

**Comment by geekyd** [comment]
@mariobehling I have made the required changes please check
https://geekyd.github.io/eventApplication

**Comment by mariobehling** [comment]
Thanks. Let's iterate from here.

**Comment by mariobehling** [comment]
Could you help with this one here please next: https://github.com/fossasia/open-event-webapp/issues/1263

**Comment by mariobehling** [comment]
After your PR the date area is no longer aligned in the same way as before neither. Opened this issue: https://github.com/fossasia/open-event-webapp/issues/1264

**Pull request merged**
