### PR TITLE
Fixed scaled out images on sample page

### LINKED ISSUE #1735: Images on sample paged are scaled out or ratio
Unfortunately this did not show up earlier as Travis did not work. Now we can see it: The images are scaled out of ratio. They are wider and faces look expanded (e.g. Google IO, FOSSASIA Summit 2010, Mozilla All Hands 2016 etc.): https://sched.eventyay.com/

Someone increased the width of the image area, but did not scale and crop the images accordingly. The image area is very wide as well and it feels unnatural.

screenshot from 2018-03-01 12-27-52

### PR DESCRIPTION
**Pull request by harsh-jindal**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Fixed scaled out images on sample page.

Screenshot:
Before:
screen shot 2018-03-02 at 8 09 44 pm
After:
screen shot 2018-03-02 at 8 09 13 pm

Fixes #1735

### CODE REVIEW

**Comment by harsh-jindal** [comment]
@agbilotia1998 How to make a deployment link?

**Comment by agbilotia1998** [comment]
@harsh-jindal deploy the overview site on github using gh-pages.

**Comment by harsh-jindal** [comment]
@agbilotia1998 I tried making the website using gh-pages . I'm able to build it but it does not reflect the changes made by me.
Can you help me out with this?

**Comment by agbilotia1998** [comment]
@harsh-jindal send me the deployment link and the repository link where you deployed the overview site.

**Comment by harsh-jindal** [comment]
This is the deployment link https://harsh-jindal.github.io/open-event/
This is the repository link https://github.com/harsh-jindal/open-event/settings

**Comment by agbilotia1998** [comment]
@harsh-jindal you didn't pull the latest changes.

**Comment by harsh-jindal** [comment]
@agbilotia1998 I didn't . That maybe the problem, I'll pull the latest changes and then make these changes.

**Pull request closed without merging**
