### PR TITLE
Added error log when unable to download jsons due to connectivity problem

### PR DESCRIPTION
**Pull request by agbilotia1998**
First step for #1455 [Error is displayed if jsons fail to download due to internet connectivity problem] 

Changes: Added error event function on request url.

Screenshots for the change
screenshot from 2017-08-26 21-26-54

### CODE REVIEW

**Comment by mariobehling** [comment]
Please fix travis.

**Comment by agbilotia1998** [comment]
@aayusharora @Princu7 please help on this , I don't know why travis is failing here.

**Comment by Princu7** [comment]
@agbilotia1998 Don't worry. Travis will be fixed as soon as the PR #1448  is merged. It will be done very quickly. Sorry for the inconvenience!

**Comment by agbilotia1998** [comment]
Okay thanks @Princu7 .

**Pull request merged**
