### PR TITLE
move source files into src directory (resolve #157)

### LINKED ISSUE #157: differentiate source and dist properly
It is bit of a mess now.

put all source into src directory. generated files go to /dist
webserver with livereload runs on /dist and NOT from source.

### PR DESCRIPTION
**Pull request by championswimmer**
Signed-off-by: Arnav Gupta <championswimmer@gmail.com>

### CODE REVIEW

**Comment by championswimmer** [comment]
Will fix https://github.com/fossasia/open-event-webapp/issues/157

**Comment by championswimmer** [comment]
@aayusharora @SilentFlame 

Let me know if gulp dist and gulp webserver are working on your systems. I have checked on two machines already,

**Comment by SilentFlame** [comment]
@championswimmer I tried on my system and yes both works fine.
just a doubt, have we intentionally changed the look of the `TRACKS` and `MAP` page as they both are now centered.

**Comment by aayusharora** [comment]
@championswimmer , I tried on two system , working fine on both.

**Comment by championswimmer** [comment]
The new Angular Material lib makes then centered.
Not intended.

Will have to make them like they were before

**Pull request merged**
