### PR TITLE
merge development to master

### PR DESCRIPTION
**Pull request by championswimmer**
Test http://opev-webgen-dev.herokuapp.com and see if it is stable enough to merge to master

### CODE REVIEW

**Comment by aayusharora** [comment]
@championswimmer Please after the merge of Track PR. Its almost done will be making it final till evening.

**Comment by championswimmer** [comment]
@aayusharora okay ! 

Also some more null track errors are coming. Need to fix that too. Let's merge this tonight then

**Comment by aayusharora** [comment]
@championswimmer The dev branch app is crashed.It is not working

**Comment by championswimmer** [comment]
@aayusharora fixed that error. try again ?

**Pull request merged**
