### PR TITLE
Adds gulp integration for issue #1105

### LINKED ISSUE #1105: Improving performance of Web app
- Please see Google page insights and improve the performance of pages.
- [ ] Approaches we can adopt for RAIL model.
- [ ] Suggest and implement the ways to improve DOM and CSSOM construction, which is currently done at once.
- [ ] Remove render-blocking CSS
- [x] Add gulp to minify the JS, CSS code for production.
- [x] Compress images and scale them to 264px rather than 300px.
- [x] Add lazy loading for images

### PR DESCRIPTION
**Pull request by geekyd**
Fixes #1105 (d)
Adds gulp minification of 

- All the js, css and html files
- Concatinates js files for each page and reduces the number of requests for js files
- Improves the pagespeed score for the webapp.

@mariobehling @aayusharora @Princu7 Please review. Thanks

Demo link:
https://open-event-web-appp.herokuapp.com

Please check pagespeed screenshots.
Screenshots: 
**Before**
screen shot 2017-03-17 at 1 45 50 am
screen shot 2017-03-17 at 1 46 00 am

**After**
screen shot 2017-03-17 at 1 41 23 am
screen shot 2017-03-17 at 1 41 37 am

### CODE REVIEW

**Comment by aayusharora** [comment]
Can you fix travis @geekyd

**Comment by geekyd** [comment]
@aayusharora Can you please help me in understanding the error ?

**Comment by geekyd** [comment]
@aayusharora The tests are running successfully on my local machine. Can you please help ?

**Comment by geekyd** [comment]
@aayusharora There is a compatibility issue with node 5 and gulp. I tested the same build on node 7 and it works without any errors.

**Comment by Princu7** [comment]
@geekyd Great work :+1: The score seems to have definitely improved over their previous values on both the mobile and the web platform which is fantastic. Regarding the compatibility issues which causing the build to fail, do you have any guesses which particular module is causing the problem. Changing the version of that could help maybe? Any luck from search on google? If nothing works, then we should maybe upgrade the node version to 7.

**Comment by geekyd** [comment]
I have tried to change the version of gulp, but it did not help. The module vinyl-fs and through2 are causing problems I have tried to install the latest versions for the application but it is not helping.

**Comment by geekyd** [comment]
@aayusharora @Princu7 It seems to work on node 5.1 and above. I have made changes to the travis.yml file and changed the version to 5.1. Its strange that its not working on node 5.

**Comment by aayusharora** [comment]
Just trying this. hope it works :+1:

**Pull request merged**
