### PR TITLE
Deployed app on google cloud flex environment

### LINKED ISSUE #921: Enable deployment of App on Google Cloud
* [ ] an app.yaml file is necessary to deploy an app on google cloud using Google Cloud SDK
this file will help deploy the Open Event webapp on Google Cloud.
* [ ] Implement storage option on Google Cloud storage in config.json

### PR DESCRIPTION
**Pull request by agbilotia1998**
Fixes #921 

Changes: Changed  app.yaml

Deployment link of cloud:https://open-event-webap-1513522507145.appspot.com/

### CODE REVIEW

**Comment by agbilotia1998** [comment]
@geekyd @mariobehling please review.

**Comment by agbilotia1998** [comment]
@geekyd @mariobehling please review.

**Comment by agbilotia1998** [comment]
@geekyd @ParthS007 please review.

**Comment by mariobehling** [comment]
Please check that Travis is working. It does not make so much sense to continue more and more without a working Travis build.

**Pull request merged**
