### PR TITLE
Show icons for main links in the top menu(#835)

### LINKED ISSUE #835: Small Resolution: Show icons for main tabs and move social icons to hidden menu
Right now in small screen resolutions the social icons show up as the main menu and the dropdown menu shows the links of the web app.

screenshot from 2016-10-04 14 27 25

The main menu should show the main links instead of external social media links. Therefore please implement as follows in small screen resolutions:
- [ ] Show icons for the main web app links in the top menu: Home, Schedule, Tracks, Rooms, Speakers
- [ ] Keep the dropdown menu as is, but move the social media icons into the last row (in one line) as in the example on http://fossasia.org 

screenshot from 2016-10-04 14 32 56

### PR DESCRIPTION
**Pull request by AdityaHirapara**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

Add icons for main links in top navigation bar for mobile view.

Fixes #835 

Deployment link: https://openeventwebapp.herokuapp.com/

Sample deployment : https://openeventwebapp.herokuapp.com/live/preview/adityahirapara2016@gmail.com/FOSSASIASummit2017/

### CODE REVIEW

**Comment by agbilotia1998** [comment]
@AdityaHirapara among the icons, home icon is not present in the samples.Please check.

**Comment by AdityaHirapara** [comment]
Actually,  event title containing that link, so i didnt add home icon

**Comment by agbilotia1998** [comment]
@AdityaHirapara among the icons, home icon is not present in the samples.Please check.

**Comment by AdityaHirapara** [comment]
Actually, Event name title has that llink, so i didnt add that icon.

**Comment by mariobehling** [comment]
While it looks nice, it is unclear to the user, what the icons stand for. I am closing this in favor of: https://github.com/fossasia/open-event-webapp/issues/1775

**Pull request closed without merging**
