### PR TITLE
radio-button-labels-clickable

### LINKED ISSUE #1535: Add Feature to make RadioButton Labels clickable.
**Actual Behaviour**

These Labels are not clickable
<ul>
<li><strong>Choose Session Style</strong> <br/>
     <ul>
         <li>Single</li>
          <li>Expandable</li>
    </ul>

</li>
<li><strong>Choose your data source</strong>
     <ul>
         <li>Upload your own JSON files</li>
          <li>API endpoint of event on OpenEvent
</li>
    </ul>
</li>
</ul>

**Expected Behaviour**

These Labels should be clickable.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by himanish-star**
Fixes #1535 
Changes: radio button labels are now clickable
You can see the changes made at https://mighty-fjord-71199.herokuapp.com/

### CODE REVIEW

**Comment by himanish-star** [comment]
@geekyd , could you please review this PR. I have also provided a link for testing the changes.

**Comment by himanish-star** [comment]
@agbilotia1998 , Then can my branch be merged now?

**Comment by himanish-star** [comment]
@geekyd , Could you please have a look at this PR.

**Comment by himanish-star** [comment]
@shubham-padia , please could you review my PR

**Comment by shikhar-scs** [comment]
Will this PR be merged or can I file another one ?

**Comment by geekyd** [comment]
@mariobehling LGTM!

**Comment by himanish-star** [comment]
@geekyd , Thank you so much for reviewing . I would always be grateful to you

**Comment by himanish-star** [comment]
@geekyd , Then shall I update my branch

**Comment by himanish-star** [comment]
@geekyd , can this be merged now ?

**Comment by himanish-star** [comment]
@geekyd Thanks for merging

**Comment by himanish-star** [comment]
@agbilotia1998 , on it

**Comment by himanish-star** [comment]
@agbilotia1998 , this error hasn't been caused by me because I reverted my changes locally and found out nothing wrong. And you can also open up the console and see that there's nothing wrong on my part of code. As io() comes out to be undefined

**Comment by himanish-star** [comment]
This error has popped up due to other PRs

**Pull request merged**
