### PR TITLE
 Component 5 : Details of Track on click

### PR DESCRIPTION
**Pull request by aayusharora**
@championswimmer  @mariobehling  @juslee  please check it here , 
This also solves Issue #295 by b1c036a.
https://drive.google.com/file/d/0BylUgB3l8Lc6a3d6bU8ya1Rwb1k/view
This is ready to merge , I have to figure out to calculate the top from window on resizing the page and automatic adjustment without page refresh. It will be done in next PR.
Updated View 
https://drive.google.com/file/d/0BylUgB3l8Lc6NlBhUzNsUmY0TnM/view

### CODE REVIEW

**Comment by aayusharora** [comment]
@mariobehling @championswimmer This also solves https://github.com/fossasia/open-event-webapp/issues/295

**Comment by mariobehling** [comment]
Which issue is this related too? Please make it easier for us and show some screenshots. I cannot see so well on the video, but what I see is that people have to click to see speakers. This should not be the case. We do not want to click. This should be discussed in the relevant issue and linked here instead of discussing this here. Please upload screenshots in issues and ask for feedback. @juslee asked at the beginning for screenshots for every feature. Thank you.

**Comment by aayusharora** [comment]
@mariobehling , This is regarding the mainissue https://github.com/fossasia/open-event-webapp/issues/268, and sub-issue  https://github.com/fossasia/open-event-webapp/issues/286 .
View 1

**Comment by mariobehling** [comment]
Ok, got it now. Thank you! I guess this is work in progress and you see what needs to be improved to achieve the final outcome.

**Pull request merged**
