### PR TITLE
compile sass in generator, and based on light/dark parameter in form

### PR DESCRIPTION
**Pull request by championswimmer**
This will take the light/dark option in form, and appropriately compile schedule.css from the required file.

### CODE REVIEW

**Comment by championswimmer** [comment]
@aayusharora merge if all looks good to you. 

I have tested and it works with both themes

**Comment by championswimmer** [comment]
## NOTE: SQUASH AND MERGE WHEN MERGING

**Comment by championswimmer** [comment]
resolves issues 
https://github.com/fossasia/open-event-webapp/issues/283
https://github.com/fossasia/open-event-webapp/issues/253

**Comment by aayusharora** [comment]
@championswimmer  , Awesome, Check both themes, it works perfectly. Able to generate both themes with different SCSS

**Pull request merged**
