### PR TITLE
Fixes #1255 Changed the footer

### LINKED ISSUE #1255: Footer: Use local license button and provide correct link
* [ ] Please use the small Creative Commons buttons instead of large buttons.
* [ ] Store buttons on the itself. Do not embed external buttons.
* [ ] Use the correct link to the actual license
* [ ] There is a link to the organizer, e.g. "© 2017 FOSSASIA and Science Centre Singapore." with a wrong link. Take out that link.
* [ ] Behind "The website and it's contents are licensed under Creative Commons Attribution 4.0 International License." or similar add the following: "The site was generated using the Open Event format on the [eventyay](https://eventyay.com) [site generator](https://webgen.eventyay.com). Please submit [issues here](https://github.com/fossasia/open-event-webapp/issues)."

### PR DESCRIPTION
**Pull request by Lplenka**
Work In Progress [#1255]

Changes: 
- [x]  Please use the small Creative Commons buttons instead of large buttons.
- [ ]  Store buttons on the itself. Do not embed external buttons.
- [ ] Use the correct link to the actual license
- [ ] There is a link to the organizer, e.g. "© 2017 FOSSASIA and Science Centre Singapore." with a wrong link. Take out that link.
- [x] Behind "The website and it's contents are licensed under Creative Commons Attribution 4.0 International License." or similar add the following: "The site was generated using the Open Event format on the eventyay site generator. Please submit issues here."

Demo-[https://demolp.github.io/](https://demolp.github.io/)

There are still certain things left to entirely close this Issue.
The second was little unclear, so I would ask again what exactly you want @mariobehling in that point.
The links in 3rd and 4rth were taken from the JSON `FOSSASIA16.zip`. They looked like correct.

 I am waiting for suggestions to complete this PR.

### CODE REVIEW

**Comment by mariobehling** [comment]
Please generate a test site with your improvements from the OSCAL data. So, I can compare the changes more easily.

If there are issues with the Open Event sample, then they need to be fixed. But it will be much easier if you can set up an OSCAL test site.

Another point: If you label your PR [WIP] many reviewers will usually not look at them until you take out [WIP]. Cheers.

**Comment by Lplenka** [comment]
@Princu7  @mariobehling  
here is the test site using OSCAL data
[https://demolp.github.io/OSCAL%202017/](https://demolp.github.io/OSCAL%202017/)

I think the links are wrong because OSCAL 2017 data doesn't have the correct data for links, they seems to be null and point to home.

To the contrary, data from [FOSSASIA16.zip](https://github.com/fossasia/open-event/blob/master/sample/FOSSASIA16.zip) holds correct data for the links and hence they work fine.

[https://demolp.github.io/FOSSASIA16/](https://demolp.github.io/FOSSASIA16/)

**Comment by geekyd** [comment]
@Lplenka Please check https://eventyay.com/api/v1/events/47
The copyright and licence details can be found in `licence_details` & `copyright` in the JSON. We extract the information from these in `fold.js` in the method `convertLicenseToCopyright`. Please apply a null check in the function to make sure that the URL does points to the correct location.

**Comment by Lplenka** [comment]
Sorry:sweat: 
:thinking:  seems like, rebasing my feature branch caused some extra commits. Closing this PR and making a new one.

**Pull request closed without merging**
