### PR TITLE
Added RedHatSummit 2017 to live site

### LINKED ISSUE #1521: Add more samples to the live site.
Need to display some more samples to the live site.

- Droidcon 2017
- RedHat 2017
- EhealthAfrica

Some of these samples are not being generated right now , I will try to fix them.

### LINKED ISSUE #1526: Add more samples to the live site.
Need to display some more samples to the live site.

1. RedHat 2017 
2. EhealthAfrica
3. Spark Summit17

 These samples are not being generated right now , I will try to fix them.

### PR DESCRIPTION
**Pull request by agbilotia1998**
Fixes #1526  .

Adds RedHat Summit 17 to the live site.

### CODE REVIEW

**Comment by agbilotia1998** [comment]
@geekyd I have corrected the RedHat Summit sample as soon as the PR on open-event gets merged the travis would proceed further.Please review.

**Comment by agbilotia1998** [comment]
@geekyd @mariobehling we can merge this now as RedHat sample correction PR is merged on fossasia/open-event

**Comment by geekyd** [comment]
@agbilotia1998 Can you generate the web app and deploy it for testing?

**Comment by agbilotia1998** [comment]
Ya Sure will do it.

**Comment by agbilotia1998** [comment]
https://agbilotia1998.github.io/RedHat-Summit17 - Deployment link with corrected JSON.

**Comment by agbilotia1998** [comment]
@geekyd please review.

**Pull request merged**
