### PR TITLE
Adds code of conduct to the web app

### LINKED ISSUE #1921: Add code of conduct to event website
**Actual Behaviour**

The JSON data contains the code of conduct field but is not shown in the generated app.

**Expected Behaviour**

The code of conduct must be shown.

**Steps to reproduce it**

Follow this URL https://raw.githubusercontent.com/fossasia/open-event/master/sample/FOSSASIASummit2017/event to check the `code-of-conduct` key-value pair.

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by agbilotia1998**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.

#### Short description of what this resolves:
Adds code of conduct to the generated event website.

#### Changes proposed in this pull request:

- Adds Code of conduct in the footer

Fixes #1921 
screenshot-2018-6-7 fossasia summit 2017

Preview Link: https://agbilotia1998.github.io/OWA-COC/

### CODE REVIEW

**Comment by agbilotia1998** [comment]
@geekyd @shubham3211 @pradeepgangwar @srv-twry please review.

**Comment by srv-twry** [comment]
BDW check the build failure :)

**Comment by agbilotia1998** [comment]
Okay @mariobehling I will make the changes.

**Comment by agbilotia1998** [comment]
@srv-twry @pradeepgangwar @ParthS007 I have made the changes please review https://agbilotia1998.github.io/OWA-COC/
screenshot-2018-6-8 fossasia summit 2017

**Comment by srv-twry** [comment]
@agbilotia1998 Looks good but fix the build and hound issues :)

**Comment by agbilotia1998** [comment]
Done :+1:

**Comment by agbilotia1998** [comment]
@srv-twry @mayank8318 @pradeepgangwar please review.

**Comment by geekyd** [comment]
@agbilotia1998 Please resolve the conflicts

**Comment by agbilotia1998** [comment]
Done :+1:

**Pull request merged**
