### PR TITLE
Adds OpenTech Summit 2016 sample to overview site

### LINKED ISSUE #1998: Add OTS16 sample to the overview site
**Actual Behaviour**

The OTS16 sample is not present in the overview site.

**Expected Behaviour**

The sample should be added.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by agbilotia1998**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.

#### Short description of what this resolves:
Adds OpenTech Summit 2016 sample to overview site.

Screenshot: 
screenshot_2018-07-10 open event webapp

Server Link: https://open-event-webapp.herokuapp.com/
API Endpoint: https://raw.githubusercontent.com/agbilotia1998/open-event/ots16/sample/OTS16
Fixes #1998

### CODE REVIEW

**Comment by agbilotia1998** [comment]
@geekyd @ParthS007 @shubham3211 please review, we need to merge https://github.com/fossasia/open-event/pull/283 before merging this PR. Thanks :)

**Comment by aayusharora** [comment]
can you please check why the build is failing @agbilotia1998  ?

**Comment by agbilotia1998** [comment]
@aayusharora we need to merge  fossasia/open-event#283 before mergin this PR  :)

**Comment by agbilotia1998** [comment]
@geekyd @ParthS007 please review https://github.com/fossasia/open-event/pull/285

**Pull request merged**
