### PR TITLE
[Fixes #1917] - Enables eslint and fixes errors

### LINKED ISSUE #1917: Enable ESlint in the project.
**Expected Behaviour**

ESlint should be enabled and errors should be removed using switches.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by agbilotia1998**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.

#### Short description of what this resolves:
Enables ESlint in the project and fixes errors using `--fix`

Fixes #1917

### CODE REVIEW

**Comment by agbilotia1998** [comment]
This PR fixes around 210 codacy issues using ESlint auto fixer. We can iterate from here in further PRs such that whenever a change is proposed in a PR, it also must resolve the linting errors and warnings in those files. What do you think @geekyd @pradeepgangwar @shubham3211?

**Comment by geekyd** [comment]
@agbilotia1998 I think we should resolve all the codacy issues related to eslint in this PR itself.

**Comment by agbilotia1998** [comment]
Okay @geekyd I will update this PR.

**Comment by agbilotia1998** [comment]
@geekyd @ParthS007 @pradeepgangwar please review.

**Comment by agbilotia1998** [comment]
Too many comments by codacy, I will be opening a new PR.

**Pull request closed without merging**
