### PR TITLE
Add audio tags and reposition audio player

### LINKED ISSUE #876: Modify design and position of the audio player
@mariobehling @aayusharora @championswimmer Your views ?

### PR DESCRIPTION
**Pull request by shubham-padia**
Attempts to resolves #876 and #891 .
Head on to http://shubhamp.in/ots/ for a demo :smiley: .

@mariobehling In my opinion, it is better to stick to the default html5 player because of the stability and more controls it provides.

### CODE REVIEW

**Comment by mariobehling** [comment]
@shubham-padia Thank you. It looks like there are some issues on the test page
* [ ] Times are mixed up, e.g. on tracks page: http://shubhamp.in/ots/tracks.html Workshops are not sorted according to time
* [ ] On speakers page, the resolution of images is very low: http://shubhamp.in/ots/speakers.html

I am still thinking about the best solution for the sound button as well.

**Comment by mariobehling** [comment]
I also added the featured info to the OTS sample JSON. Please use the latest version for site generation of the next version.

**Comment by shubham-padia** [comment]
@mariobehling 

> On speakers page, the resolution of images is very low.
The images in the ots sample itself are of dimensions 100*100 as compared to 300*300 dimensions of fossasia sample. the resolution is low because of that.

I am looking into the other issues asap.

**Comment by shubham-padia** [comment]
@mariobehling about the mix-ups in time, seems like there are multiple issues in https://github.com/shubham-padia/open-event/blob/master/sample/OTS16/tracks . Fixing them right away :smiley: .

**Comment by mariobehling** [comment]
Ok, yes, I missed that. I opened an issue about this here: https://github.com/fossasia/open-event/issues/114

**Comment by shubham-padia** [comment]
@mariobehling Apparently the mixup in times was not a ots sample issue, it was a webapp issue, the sessions in each track were not being sorted previously. I've updated the code and the sample site, please check the links once again.

**Comment by mariobehling** [comment]
Please check: All sessions have the same color now.

**Comment by shubham-padia** [comment]
@mariobehling All of them have the same color `#3DC8C3` right now in the sample as can be seen on https://github.com/fossasia/open-event/blob/1897f59dc6e30b6e012a85cecd038703bfb4acfe/sample/OTS16/tracks. 

You can also check a previous version of ots site at http://shubhamp.in/ots2/tracks.html and colors were same in that one too.

**Comment by mariobehling** [comment]
Ok, thanks. Please help to change the color codes in the sample, if possible.

**Comment by mariobehling** [comment]
Good job!

**Comment by shubham-padia** [comment]
@mariobehling 

about  
>  change the color codes in the sample

Are there any standards to follow for the color codes or should i set them as i see fit ?

**Comment by mariobehling** [comment]
@shubham-padia No, there are not any standards. It depends on the choices of the organizer.

**Pull request merged**
