### PR TITLE
#1029: fixed inactive generate button on entering wrond email address

### PR DESCRIPTION
**Pull request by anu-007**
fixed inactive webapp generate button if user enter a wrong email address.

### CODE REVIEW

**Comment by Princu7** [comment]
I am sorry but I don't see any changes. It seems like some commits are lost. Please check it. Thanks!!

**Comment by anu-007** [comment]
@Princu7 check in form.js i have moved these three lines inside if(check) condition which are previously outside the if(check) condition.
  $('.generator-progress').show();
    $('#generator-progress-bar').show();
    $('#btnGenerate').prop('disabled', true);

**Comment by Princu7** [comment]
@anu-007 Ah. Sorry for the confusion :smile: Could you please provide a test server where we can test this out, please? Thanks!!

**Comment by anu-007** [comment]
@Princu7 here is the test server ( https://fast-coast-48490.herokuapp.com/ ).thanks!

**Comment by Princu7** [comment]
Thanks for setting up the test server. I tried to reproduce the issue but it doesn't seem to work correctly. Could you please recheck?
https://www.useloom.com/share/049abc943f5f4f5fa2b9e108169f3e63

**Comment by anu-007** [comment]
@Princu7 sorry for the wrong link you can test it here ( https://polar-hamlet-90903.herokuapp.com/ ).Thanks!!

**Comment by Princu7** [comment]
Works Good. Thanks!!

**Pull request merged**
