### PR TITLE
Added microlocation in fold by tracks

### LINKED ISSUE #1118: Do not show unscheduled sessions
The sessions in the exhibition track are unscheduled, but they still show up. This is related to the API showing data that is still unscheduled. So, this issue needs to be tackled together. There is a corresponding issue here: https://github.com/fossasia/open-event-orga-server/issues/3277

### PR DESCRIPTION
**Pull request by Princu7**
Fixes #1118
* Earlier, the unscheduled sessions showed up on the generated website

* This pull request fixes this problem and only shows those sessions which have been scheduled by the organizer

* The decision regarding whether a session has been scheduled is being done on the microlocation field of the session. If the field is null, then it means that the session is unscheduled and vice-versa.

* Deployed site: https://princu7.github.io/eventSiteWebApp
* Test Server: http://secure-meadow-20680.herokuapp.com

@aayusharora @mariobehling Please Review.

### CODE REVIEW

**Comment by Princu7** [comment]
**Screenshots**

`Old`
The unscheduled session 'Blockchain Technologies - Hyperledger' by 'Nikolay Vlasov' shows up on the event website. The microlocation field of the session is set to null.

screenshot from 2017-04-06 21-00-18

`New`
screenshot from 2017-04-06 21-00-49

**Comment by shubham-padia** [comment]
@princu7 It would be great if you could put a check for rejected and pending sessions, If it is not implemented already. It is related to https://github.com/fossasia/open-event-orga-server/issues/3277 which was closed recently.

**Comment by Princu7** [comment]
@shubham-padia Oh. Ok. Thanks. Will do so :)

**Comment by Princu7** [comment]
I have added the additional checks. Should be fine now :)

**Pull request merged**
