### PR TITLE
Unnecessary Margins in Sessions/Speakers details

### PR DESCRIPTION
**Pull request by PiotrKowalski**
I didn't want destroy anything so I created two new things in .css and set one of them to !important 
If you want I can look for these two things and change it in original form.
https://github.com/fossasia/open-event-webapp/issues/83

### CODE REVIEW

**Comment by PiotrKowalski** [comment]
Indeed, you think about it? http://scr.hu/3e1h/ryii6
I will repair this. Give me a sec.

**Comment by PiotrKowalski** [comment]
Fixed my mistakes. I think that it is better now.

**Comment by PiotrKowalski** [comment]
Of course:
http://scr.hu/3e1h/voyyx
http://scr.hu/3e1h/d9a6w
http://scr.hu/3e1h/k58nr

**Comment by MaxBorsch** [comment]
Theres also a subtitle under the title that just is empty usually. Would it be visible? Also I think I fixed it with a better way.

**Pull request closed without merging**
