### PR TITLE
#1136 : tweet overflow on homepage

### LINKED ISSUE #1136: Text overflow on Tweeter section of Homepage
The dynamically appended tweets sometimes exceeds the width of container and results in a horizontal scrollbar on mobiles.

### PR DESCRIPTION
**Pull request by sumedh123**
This is how it looks now.  Think it fixes #1136 
fossasia2

### CODE REVIEW

**Comment by geekyd** [comment]
@sumedh123 Please use the colours specified in config.scss instead of using colour codes. Thanks :)

**Comment by sumedh123** [comment]
@geekyd  Sorry I kept that for test purpose only. forgot to remove that. fixed it now.

**Comment by Princu7** [comment]
@sumedh123 Nice work. Could you please squash the commits? Thanks!!

**Comment by mariobehling** [comment]
@sumedh123 Thanks. Please always add in the description "Fixex #IssueNumberHere". This helps reviewers to speed up the process. Thanks!

**Comment by sumedh123** [comment]
Sure @mariobehling . Shall I amend the commit again or is it okay?

**Comment by Princu7** [comment]
@sumedh123 Thanks for squashing the commits. Please also amend your commit message to something more descriptive like "Add clear property to avoid tweet overflow on homepage". Also, it is considered a good habit to write 'Fixes #IssueNumber' in the description of the PR(not in the commit message). This way, the related issue automatically gets closed when the PR gets merged.

**Comment by sumedh123** [comment]
Done @Princu7

**Comment by Princu7** [comment]
@sumedh123 The work is already completed. Thanks. I am sorry but it seems like you misunderstood. You should add "_Fixes #IssueNumber_" in the description of the PR in which you are showing the correct screenshot. Don't add it in the commit message. The issue number in a commit message is just noise and doesn't add any information. Instead use a declarative commit message describing _what_ you did in the commit.
These two links are worth a read. Please go through them. Thanks!!
https://github.com/blog/1506-closing-issues-via-pull-requests
https://chris.beams.io/posts/git-commit/

**Comment by sumedh123** [comment]
The article was of great use @Princu7 . Thanks :)

**Comment by Princu7** [comment]
No problem. Glad you found it useful :)

**Pull request merged**
