### PR TITLE
Improves sessions in tracks and rooms page

### LINKED ISSUE #1208: UI: Sessions in tracks and rooms page not displayed properly
It seems that the session in the rooms and tracks page are not displayed properly please check the screenshots.

Link : http://fossasia.github.io/open-event-webapp/
**Actual Behaviour**
screenshot 27

**Expected Behaviour**

screenshot 28

### PR DESCRIPTION
**Pull request by geekyd**
Fixes #1208 

Changes: Improves the layout of sessions in tracks and rooms page.
**Previous design**

**Screenshots for the change:** 

screen shot 2017-04-03 at 1 33 22 pm

@mariobehling @aayusharora @Princu7 Please review this. Thanks

### CODE REVIEW

**Comment by geekyd** [comment]
@aayusharora It seems that the commas have disappeared since #1207, I think we should consider adding selenium or phantomjs for the browser testing. It will avoid repeated re-doing the same functionality. What do you think?

**Comment by Princu7** [comment]
@geekyd +1 Exactly. I also mentioned about it in my proposal :smile: . Right now, after every commit related to the web-app, it is very hectic to go through the entire site manually and check whether all the required things are working or not. We would be able to automate the entire process through Selenium. It could check for all the dead links and other functionalities.

**Comment by geekyd** [comment]
@Princu7
Yes I agree. Great feature to add for the contributors and maintainers 👍

**Comment by geekyd** [comment]
@aayusharora @Princu7 Please check https://open-event-web-appp.herokuapp.com

**Comment by aayusharora** [comment]
@geekyd @Princu7 Selenium is the requirement now, we have to make it an issue. Thanks.

**Pull request merged**
