### PR TITLE
Fixed Cancel Generation Issue

### PR DESCRIPTION
**Pull request by SparshBansal**
#952 Solved

Now the website build is canceled on pressing the cancel button. There also should not be any problem with multiple users.

### CODE REVIEW

**Comment by aayusharora** [comment]
Thanks @SparshBansal But can you please mention it is referred too.

**Comment by SparshBansal** [comment]
@aayusharora  , I am sorry , i didn't get what you meant.

**Comment by aayusharora** [comment]
@SparshBansal Please refer the Issue number in the description of this PR.

**Comment by SparshBansal** [comment]
Issue #952 Solved

**Comment by aayusharora** [comment]
Ok Cool Thanks

**Comment by aayusharora** [comment]
@SparshBansal Can you please squash the commits.

**Comment by Princu7** [comment]
@SparshBansal Hey. Thanks for the request. To make reviewing easier, could you please host the test application on Heroku, please?

**Comment by SparshBansal** [comment]
@aayusharora , I have squashed the commits and will send a new PR

**Comment by SparshBansal** [comment]
@Princu7 , I will host it on heroku for review

**Comment by SparshBansal** [comment]
@Princu7 I have deployed it on heroku and here is the link : https://safe-sea-55983.herokuapp.com/

**Comment by aayusharora** [comment]
Nice Work @SparshBansal

**Comment by geekyd** [comment]
@SparshBansal Before sending a PR please let us know that you are working on the issue.
I checked the demo link, the generation does not stop immediately if X is clicked.
You can use a variable in socket object to keep the status.
Please look into it.

**Comment by aayusharora** [comment]
@SparshBansal There are bugs in this PR. @geekyd Thanks for reporting.
Reverting this :(

**Comment by SparshBansal** [comment]
@aayusharora
@geekyd 
It doesn't stop immediately because when the user issues a cancel request it is send to the back end server and if the server has started some asynchronous operation in the asynchronous series then I can't cancel it in between. I cancel it between 2 asynchronous steps. 
That's why it doesn't immediately cancel the build process. 
Also I notify the frontend client of cancellation only when it has actually cancelled it in the backend. That is between 2 asynchronous steps. 
I don't know how to cancel an asynchronous operation in between. Could you please guide me on that.

**Comment by geekyd** [comment]
@SparshBansal We can hide the progress bar and the status bar as soon as the user hits cancel, and the rest will be handled by the backend.

As soon as x is clicked 
**Hide the progress bar and the status text**

As soon as the user uploads zip 
**show the progress bar and the status text**

@aayusharora Do you agree?

**Comment by SparshBansal** [comment]
Yeah we can do that

**Comment by SparshBansal** [comment]
@geekyd I think we also disable the upload zip element till the build gets cancelled in the backend and we receive an acknowledgement at the client side

**Comment by SparshBansal** [comment]
@geekyd  Also I have noticed a bug while running the dev version hosted on heroku , If I cancelled uploading in the middle and retried again , it started from the same point it left off thus suggesting that the upload was not cancelled.

**Comment by Princu7** [comment]
@SparshBansal The zip file upload is definitely canceled. It might be starting from middle maybe because of caching issue :)
To be more precise, it is because of this line
`uploader.resetFileInputs = false`
If you set it to true, it should be starting from beginning. 
Will check the test server soon. Net speed a bit slow now :smiley:

**Pull request merged**
