### PR TITLE
Code cleanup and New Branch GSOC16/ui

### PR DESCRIPTION
**Pull request by aayusharora**

### CODE REVIEW

**Comment by aayusharora** [comment]
@championswimmer , @juslee , Please see to it . 
This will be a branch for version 1 that will be integrated with master in every week .

**Comment by championswimmer** [comment]
The 'cleanup' commit just delets all files ? 
Why not start an orphan brach ?

**Comment by aayusharora** [comment]
@championswimmer , what after the merge then ?
1 . The merge will consist of previous files also , which will create confusion . Lot of changes in previous files.
2 .Gulp is removed which have to be added later .

The orphan branch after will consist of content of both the branches .
We can take GSOC16/ui separate without any hinderance .

**Comment by championswimmer** [comment]
We don't need to merge
rename master -> gsoc2015
rename gsoc2016 -> master

**Comment by mariobehling** [comment]
@aayusharora @championswimmer Please get started. Use the Open Event Scraper as a basis, build a UI and make it possible to render any event using the same JSON format. Please do start now.

**Comment by juslee** [comment]
I'll close this PR first and you should submit a new PR. Thanks.

Please resolve all conflicts in gsoc branch with master first.

**Pull request closed without merging**
