### PR TITLE
fixes #1007 restricts only zip to be uploaded

### LINKED ISSUE #1007: Bug: Generator Logs and File Upload
- [ ] The user should not be able to upload any file if it is not `.zip` extension, show `message to upload zip extension`
- [ ] Clear all logs messages after clicking cross button
bug

### PR DESCRIPTION
**Pull request by geekyd**
@mariobehling @aayusharora @Princu7 
Please review the code.

Live demo at 
https://open-event-web-appp.herokuapp.com/

### CODE REVIEW

**Comment by Princu7** [comment]
@geekyd Looks nice. It would be better if you could read about the `choose` event in the `socket-io-file- upload` documentation. It is fired right before the start event and we could verify the file name at that moment. If the file is not zip, then we can return false and no further events will be fired. This way, code related to the start event remains unchanged
What do you think? Would love your opinions.
https://www.npmjs.com/package/socketio-file-upload#choose
Also squash your commits into one. Thanks!!

**Comment by geekyd** [comment]
@Princu7 Thats great idea. I read the doc and I'm implementing `choose` event.

Thank you for the feedback 😄

**Comment by geekyd** [comment]
@aayusharora Please review this. :)

**Comment by aayusharora** [comment]
Thanks you :)

**Pull request merged**
