### PR TITLE
add ftp auto deploy and make audio file download synchronous

### LINKED ISSUE #861: Auto-deploy sample of Open Tech Summit to Heroku
The sample of the OpenTechSummit has a lot of audio files, that are too big to deploy to Github without Large File Support. Therefore please auto-deploy the sample on pull request merges to Heroku.

The sample file is here: https://github.com/fossasia/open-event/tree/master/sample/OTS16

### PR DESCRIPTION
**Pull request by shubham-padia**
Resolves #861 and #871. In reference to #874 , only audio file download has been made synchronous as it gets things working.
Check the demo at http://shubhamp.in/ots2/ . 

### DO NOT MERGE
do not merge before the ftp link has been changed along with protocols.

### CODE REVIEW

**Comment by mariobehling** [comment]
@shubh1m Thanks. Currently I cannot find an audio play or upload option on the sample site.

**Comment by shubham-padia** [comment]
@mariobehling The audio play is working fine , e.g see http://shubhamp.in/ots2/tracks.html#desc-40.
And yeah wait for the page to load completely ( until the reload button appears on chrome )

**Comment by mariobehling** [comment]
Ok, thanks. Please also implement for other pages and let's think a bit about the design and/or position of the player.

**Comment by shubham-padia** [comment]
Okay, cool :+1: , by `other pages`, which do you specificically mean

**Comment by aayusharora** [comment]
@shubham-padia  Please set <audio preload = "none">

**Comment by mariobehling** [comment]
> by other pages, which do you specificically mean , i'm not aware with how it was implemented earlier.

tracks, room, schedule page. Thank you.

**Comment by shubham-padia** [comment]
> Please also implement for other pages and let's think a bit about the design and/or position of the player.

@mariobehling
- Audio tracks have been added to room and schedule ( expand to see the audio ) page also. Please check the above given link once again .
- I'll open an issue about the design and position issues,  once this is merged and we can work on them from there.
- Also #874 is a very high priority issue requiring significant changes to the code in order to get the webapp properly functioning and in order to maintain proper workflow, it is essential  that this PR is merged first.

Thank You .

**Comment by shubham-padia** [comment]
@mariobehling kindly give your feedback :smiley:

**Comment by mariobehling** [comment]
Ok, good job! Keep it up.

**Pull request merged**
