### PR TITLE
Adds share feature to webapp

### PR DESCRIPTION
**Pull request by geekyd**
Solves #1055 Adds share feature to the generated web-app.

Screenshot:
screen shot 2017-03-04 at 2 03 25 am
screen shot 2017-03-04 at 2 03 46 am

Test server:
https://open-event-web-appp.herokuapp.com/
@mariobehling @aayusharora @Princu7 Please review thanks.

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you. When I click on "Share" it moves the page up. This bug might have existed before, but as you are changing the implementation, you should not "include" this bug. Please ensure, the page does not move when the user clicks "share".

**Comment by geekyd** [comment]
@mariobehling Fixing the issue. Thanks

**Comment by geekyd** [comment]
@mariobehling @aayusharora @Princu7 Please check https://open-event-web-appp.herokuapp.com

**Comment by Princu7** [comment]
Nice work :smiley:

**Comment by Princu7** [comment]
@geekyd Nice work :smiley: A small tip: When dealing with issues related to the generated websites, it is better to give the link to the live gh-pages of the generated site. This way, we don't have to generate the whole site by ourselves again :+1:

**Comment by geekyd** [comment]
@Princu7 Thanks. I will deploy the web-app directly from the generator next time. I will keep it in mind.

**Comment by championswimmer** [comment]
looks fine to me now

**Comment by geekyd** [comment]
@championswimmer Thank you!

**Pull request merged**
