### PR TITLE
Solved the line issue and the scroll issue

### PR DESCRIPTION
**Pull request by Princu7**
Fixes the issue #866 . 
Test it here
https://princu7.github.io/websiteTest/
Please review. Thanks!!

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you. Please check about hound-ci issues. Cheers.

**Comment by Princu7** [comment]
@mariobehling
 I have made some changes but the houndci issues are nothing to worry about. They warn about the not defined $ symbol. Since the $ symbol comes from the jquery library which will also be included in the file in which we are including this very file itself so there will be no problems. Also the rest of the code is in the same veins with the previous structure of the code.

**Comment by mariobehling** [comment]
Yes, I know, but we should tackle some of these as well. Let's proceed step by step. Thank you.

**Comment by Princu7** [comment]
@mariobehling Makes perfect sense. Focus on big issues and then shoot down all the smaller ones. :+1:

**Pull request merged**
