### PR TITLE
Editing of documentation

### PR DESCRIPTION
**Pull request by meets2tarun**
Heroku app installation guide is completed to give the full steps as others server heroku installation guide.
[Link_to_edit](https://github.com/meets2tarun/open-event-webapp/blob/development/docs/INSTALLATION_HEROKU.md)

Local Machine deployment guide is edited to rectify the error if one get. 
[Link_to_edit](https://github.com/meets2tarun/open-event-webapp/blob/development/docs/INSTALLATION_LOCAL.md)

### CODE REVIEW

**Comment by aayusharora** [comment]
Hi, Thanks  @meets2tarun . Which issue is this related to?

**Comment by meets2tarun** [comment]
@aayusharora  Heroku app installation is explained more further to help the user to deploy it correctly.
And while local deployment it is giving fetch error while fetching from https, so I set it to http.

**Comment by Princu7** [comment]
@meets2tarun Thanks for the request. It's always recommended to open an issue before sending a PR. Thanks!!

**Comment by meets2tarun** [comment]
@Princu7  I will take care of such in future.

**Comment by Princu7** [comment]
@meets2tarun Please squash your commits. Thanks!!

**Comment by meets2tarun** [comment]
@Princu7 I will

**Pull request closed without merging**
