### PR TITLE
Improved search in the generated website

### PR DESCRIPTION
**Pull request by Lplenka**
Fixes [#1304]

The search in schedule, tracks, speakers & rooms page was a little faulty. 

e.g. If you search "Keynote", then you get the results as soon as you type till "Keyn" and obviously when you type "keynde", you won't get the results. But when you erase the added wrong characters and search string becomes "Keyn", you still don't get results even after writing full search string "keynote", you won't get the results. Here is the gif showing the error. Please open to see the error.

errorinsearch

This PR fixes that error.

Before Changes:
[https://demolp.github.io/FOSSASIASummit/index.html](https://demolp.github.io/FOSSASIASummit/index.html)

After Changes:
[https://demolp.github.io/FOSSASIAnew/index.html](https://demolp.github.io/FOSSASIAnew/index.html)

### CODE REVIEW

**Comment by geekyd** [comment]
@Lplenka Can you please specify the issue which you are fixing with this PR?

**Comment by Lplenka** [comment]
@geekyd no such issue was reported :sweat_smile: . I found this and went for the PR to solve the issue. The issue is as much I have explained above.

**Comment by mariobehling** [comment]
@Lplenka Good job! But, for a number of reasons we require devs to open issues before they make a PR. Please have a look at our best practices here: http://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

Some reasons: It helps to align all developers and keep the communications flowing. Developers can give feedback to specific points and discuss best approaches where relevant. It also helps to keep a documentation of activities. You will probably find a lot of projects where this is done like that and in companies like IBM they also work in that way. So, please make it easy and transparent what is being worked on and open an issue and match this issue in the pull request.

Thanks.

**Comment by Lplenka** [comment]
@mariobehling sure, will open an issue now for this.

**Comment by mariobehling** [comment]
Well-Done.

**Comment by Lplenka** [comment]
Thanks @mariobehling  @geekyd

**Pull request merged**
