### PR TITLE
link highlighted on click share

### LINKED ISSUE #2022: make share highlighted
**Screenshots of the issue**
makehigh

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by shubham3211**
Fixes #2022 
Sample:-https://shubham3211.github.io/calendar-fix/index.html

### CODE REVIEW

**Comment by agbilotia1998** [comment]
@shubham3211 thanks for the PR :)
Can you please make a small change, instead of just selecting the link make changes so that it is copied to clipboard automatically, just like while sharing google docs document using a sharable link and add a tooltip or pop-box to notify the user of the same.

**Comment by shubham3211** [comment]
@agbilotia1998 done :+1:

**Comment by agbilotia1998** [comment]
@shubham3211 great!! Looks good to me, can we change the tooltip title to `Link copied to clipboard`.

**Comment by shubham3211** [comment]
@agbilotia1998 done

**Pull request merged**
