### PR TITLE
Removing inline CSS from handlebars and adding it to SASS

### LINKED ISSUE #990: SASS optimizations
- [ ] Remove redundancy by using SASS mixins
- [ ] Adding repeated values like padding, margin, colors etc to config.scss
- [x] Removing inline CSS from handlebars and adding it to SASS.

### PR DESCRIPTION
**Pull request by utkarshnath**
Fixed #990 (c)
https://guarded-inlet-13297.herokuapp.com/
@aayusharora please review

### CODE REVIEW

**Comment by geekyd** [comment]
@utkarshnath Great work. Can you please use the values of colours defined in config.scss for assigning colours to the element. Thanks

**Comment by utkarshnath** [comment]
@geekyd done

**Comment by utkarshnath** [comment]
@aayusharora plz review

**Comment by aayusharora** [comment]
@utkarshnath Please remove Merge conflicts

**Comment by utkarshnath** [comment]
@aayusharora conflicts resolved

**Comment by aayusharora** [comment]
There are still conflicts :( @utkarshnath

**Comment by utkarshnath** [comment]
@aayusharora resolved conflicts

**Comment by geekyd** [comment]
@utkarshnath Please squash the commits. Thanks :)

**Comment by geekyd** [comment]
@utkarshnath Please resolve the conflicts and squash the commits. Thanks :)

**Pull request closed without merging**
