### PR TITLE
#1036:Fixed changing data source will make the app work accordingly

### PR DESCRIPTION
**Pull request by shashanktatti**
The generate button and the other html elements will be disabled/enabled according to the situation so as to make the app work correctly.

#1036

### CODE REVIEW

**Comment by Princu7** [comment]
@shashanktatti Remove the swap files and squash your commits :)

**Comment by mariobehling** [comment]
Thanks: Please add the issue you are solving in the description to make it easier for reviewers. Cheers.

**Comment by shashanktatti** [comment]
@mariobehling sir , link to the issue [#1036](https://github.com/fossasia/open-event-webapp/issues/1036)

**Comment by aayusharora** [comment]
Please provide a hosted URL @shashanktatti for this.

**Comment by shashanktatti** [comment]
@aayusharora please view the app at [heroku](https://afternoon-earth-69927.herokuapp.com/)

**Comment by aayusharora** [comment]
@shashanktatti Please resolve the conflicts.

**Pull request closed without merging**
