### PR TITLE
[DO NOT MERGE YET] use angular2-seed to move to angular2

### PR DESCRIPTION
**Pull request by championswimmer**
Signed-off-by: Arnav Gupta <championswmmer@gmail.com>

### CODE REVIEW

**Comment by championswimmer** [comment]
I'll line up more commits before it's ready to merge. 
Right now it is just the default angular2-seed source code.

**Comment by championswimmer** [comment]
@aayusharora if you want to understand the angular2 structure and get acquainted with the source, 

Take a look at https://github.com/championswimmer/open-event-webapp/tree/angular2-seed-staging

```
npm install
npm run serve.dev
```

**Comment by juslee** [comment]
Merge?

**Comment by championswimmer** [comment]
Yes. Let's merge this if all looks good to you and @aayusharora

**Comment by aayusharora** [comment]
Closing this for now :)

**Pull request closed without merging**
