### PR TITLE
Color codes with Title on Room page [ Do not Merge ]

### PR DESCRIPTION
**Pull request by aayusharora**
Issue #504

### CODE REVIEW

**Comment by championswimmer** [comment]
Do not submit comment before image has been uploaded as attachment :p

**Comment by aayusharora** [comment]
@championswimmer  Yeah :p

**Comment by championswimmer** [comment]
@aayusharora does the color code box stay sticky ? or does it scroll away when we scroll down ?

**Comment by championswimmer** [comment]
## hold this merge before #510 is done

**Comment by aayusharora** [comment]
It scroll away .. @championswimmer

**Comment by championswimmer** [comment]
@aayusharora can you make it stick ? 
It's good to have the glossary always available

**Comment by aayusharora** [comment]
@championswimmer I have already given a thought to that. But when we think this for small-screens the sticky track-bar will fail because in small screens the track-bar should come below the tracks above the footer.
This is the reason why sched.org does not keep it sticky. If you can think of an alternate approach please mention.

**Comment by aayusharora** [comment]
@championswimmer Sorry for merging it on my own but that was urgent to check some of the code changes. This was pending for three days and already reviewed by you. Please make a separate issue for sticky track-title if it is needed.

**Pull request closed without merging**
