### PR TITLE
Add compression middleware

### PR DESCRIPTION
**Pull request by championswimmer**
Signed-off-by: Arnav Gupta <championswimmer@gmail.com>

### CODE REVIEW

**Comment by championswimmer** [comment]
@aayusharora Please check out differences between

https://opev-webgen-dev.herokuapp.com/ (this PR)
and 
http://open-event-generator.herokuapp.com/ (master)

**Comment by aayusharora** [comment]
@championswimmer Can you please see this before I compare 

This comes here https://opev-webgen-dev.herokuapp.com/

**Comment by aayusharora** [comment]
@championswimmer  it does not work for me. We have to figure out a solution as early as possible. This is taking 13 min to finish loading. The data will increase and hence the loading time. The only drawback here is we can't load data with scrolling. Loading all the data at once is the major problem of the page
Here is the snapshot.Please give suggestions.
fail

**Comment by aayusharora** [comment]
@championswimmer Though an improvement is there but that is not sufficient to work
This PR


Master

**Comment by championswimmer** [comment]
As per my tests across 3 browsers, it is decreasing load time by 20%
So I am merging this. We will have to look at even more methods to increase performance

**Pull request merged**
