### PR TITLE
added language support

### LINKED ISSUE #1002: Multilingual support : Adding language support to generated Webapp
After generating app, participant can change the language of the pages with a selectbox.
Things to Consider
1. The webapp generated are static pages that work offline.

@Princu7 @mariobehling What are your views ?

### PR DESCRIPTION
**Pull request by utkarshnath**
fixed #1002

### CODE REVIEW

**Comment by aayusharora** [comment]
Please provide a Hosted version of the app @utkarshnath

**Comment by utkarshnath** [comment]
@aayusharora will this work or I should host it

ezgif-1-64894c9287

**Comment by Princu7** [comment]
@utkarshnath The gif looks nice but a hosted version of the app would be even better. There are many things which sometimes go unnoticed in the screenshots or the gif. Just deploy the sample on your gh-pages. Thank you so much!!

**Comment by utkarshnath** [comment]
@aayusharora @Princu7 @mariobehling deployed on Heroku
https://desolate-meadow-51072.herokuapp.com/

**Comment by aayusharora** [comment]
@utkarshnath You still have old code, It is reflecting with social sharing icons in your hosted version.
Please pull the new code.

**Pull request closed without merging**
