### PR TITLE
Small hover fix 

### PR DESCRIPTION
**Pull request by aayusharora**
snap
issue #786

### CODE REVIEW

**Comment by mariobehling** [comment]
@aayusharora Please see my comment here: https://github.com/fossasia/open-event-webapp/issues/786#issuecomment-257322344

It would be good to get the gray background back for this feature as it was some time ago.

**Comment by aayusharora** [comment]
@mariobehling  I have solved the two points out of the three, will change the background to gray as well :)

**Comment by aayusharora** [comment]
@mariobehling The background as shown in snapshot is gray and bit transparent, Do we need something else to merge this.

**Comment by mariobehling** [comment]
@aayusharora Yes, the actual page that is currently "active" should have a darker gray color.

**Comment by mariobehling** [comment]
Ok, let's do the next steps in the following PR. I am merging this for now. Thank you.

**Pull request merged**
