### PR TITLE
implemented basic service worker

### PR DESCRIPTION
**Pull request by anu-007**
Fixes #[1247]

Changes: [Added a basic service worker for caching some file to enable viewing offlilne]

### CODE REVIEW

**Comment by Princu7** [comment]
@anu-007 Thanks. Great work. Please look at the codacy issues and see if you could remove them. Otherwise, it looks good. We would need to structure it a bit more and add other details but this seems great for starting.

**Comment by anu-007** [comment]
@Princu7 ok I will look into codacy issue and yes the current implementation service-worker is very basic and other progressive enhancements can be easily applied by extending it further. And as you said it supports basic installation and fewer cache contents. Thanks!!

**Comment by Princu7** [comment]
@anu-007 Forgot to mention but please also post a live link where we can test it. Thanks!

**Comment by geekyd** [comment]
@anu-007 Please provide the link to gh-page for test. Thanks!

**Comment by anu-007** [comment]
@Princu7 @geekyd this service-worker works well locally but on deployment it cause many problems also the web app uses gulp as a build tool so, I redesigned it using sw-precache as it works very well with gulp, it is almost done I will send a PR by tomorrow with links of deployment.Thanks!!

**Comment by mariobehling** [comment]
@anu-007 Thanks for engaging in this project.

We actually engaged you in the Front-end project and I am not sure, how you find the time to work on this project here. Where-as there are tons of super urgent issues and bugs to be solved, it seems like you rather take your time for issues that are not high priority.

So, not sure, what is your goal here.

**Comment by anu-007** [comment]
@mariobehling okay, I will focus on front-end project.
@Princu7 as far as the status of this issue is concern I am able to cache all the files with sw-precache but not able to handle 'fetch' event with current service-worker, all the work progress can be found here ( https://github.com/anu-007/open-event-webapp/commit/7507c383b20e3e5f68c3f4019d84dfb3a8a8a047 ) if you like you can have a look at it.Closing this PR.

**Comment by Princu7** [comment]
@anu-007 Ok. No problem at all. Thanks!!

**Pull request closed without merging**
