### PR TITLE
Show name, affiliation and link on dropdown speakers info

### LINKED ISSUE #783: Show name, affiliation and link on dropdown speakers info
When the dropdown info of the speaker is shown it does not show the speaker's name and affiliation.

Please add the info into the gray area and a share link screenshot from 2016-09-05 19 32 18

screenshot from 2016-09-06 09 16 14

### PR DESCRIPTION
**Pull request by shubham-padia**
Intends to resolve #783 .

Result:

screenshot from 2016-09-07 20-28-19

### CODE REVIEW

**Comment by aayusharora** [comment]
@shubham-padia The issue says to add name and org in gray area. According to me it's not looking good center aligned.

**Comment by mariobehling** [comment]
Nice. Next steps:
* [ ] Yes, please keep the text alignment.
* [ ] Add following text into gray area "Abdul Rauf (Mozilla)"

**Comment by shubham-padia** [comment]
@mariobehling Updated the PR, looks like this now,

screenshot from 2016-09-07 23-29-03

screenshot from 2016-09-07 23-28-46

**Comment by mariobehling** [comment]
Ok, thanks for the screenshot. I think you are right, it looks too squeezed. Please
* [ ] move the sharing link into the social media area
* [ ] No need to repeat the name in the white area

**Comment by shubham-padia** [comment]
@mariobehling In the current social media area, there is no space left for putting the share link due to unnecessarily large spacing between the icons.

Right now : 

screenshot from 2016-09-08 01-05-19

1st approach : 
If we reduce the unnecessary spaces :
screenshot from 2016-09-08 01-10-25

2nd Approach: 
Alternatively without removing the spacing, placing the share link on a new line can also work :
screenshot from 2016-09-08 01-17-20

Should I go with approach 1 or 2 ?

**Comment by mariobehling** [comment]
@shubh1m Thank you. There is probably no perfect solution, but let's try the 1st approach and see how it works for the users, I would say.

**Comment by shubham-padia** [comment]
@mariobehling updated the code according to approach 1. Please review.

**Comment by mariobehling** [comment]
Thank you!

**Comment by mariobehling** [comment]
So, looking at the details I see you are not using US/British punctuation rules and we can enhance some details. Created a follow up issue. Thank you: https://github.com/fossasia/open-event-webapp/issues/791

**Pull request merged**
