### PR TITLE
Improves loding speed of all pages

### LINKED ISSUE #1266: Improving loading speed of the app
Currently the whenever the page is loaded, the display() function is executed, which iterates over every session on the page to add star to the bookmarked sessions. This takes time as we iterates over DOM elements. The load time increases linearly with the number of sessions. 

One good solution would be to iterate the array stored in localStorage, instead of DOM elements.
Please suggest your solutions.

### PR DESCRIPTION
**Pull request by geekyd**
Fixes #1266 

Changes: Improves loading speed of schedule, tracks and rooms page by replacing the `display()` function which is triggered on first load with `initPage()` which iterates over array instead on DOM objects to add stars to all bookmarked sessions .

Demo : 
https://geekyd.github.io/eventApplication

### CODE REVIEW

**Comment by aayusharora** [comment]
Thankyou @geekyd Please provide a live version to test.

**Comment by geekyd** [comment]
@aayusharora Please check this
Live demo link:
http://open-event-web-appp.herokuapp.com

**Comment by aayusharora** [comment]
Please provide gh-pages link. @geekyd

**Comment by geekyd** [comment]
@aayusharora please check https://geekyd.github.io/eventApplication

**Comment by aayusharora** [comment]
Thanks :)

**Pull request merged**
