### PR TITLE
Added Name, Organisation and Track color

### PR DESCRIPTION
**Pull request by aayusharora**
Issue #578

### CODE REVIEW

**Comment by mariobehling** [comment]
* [ ] lots of hound-ci issues
* [ ] why is track heading red? It should not be.
* [ ] first text line next to picture is not properly aligned

**Comment by aayusharora** [comment]
@mariobehling
 **lots of hound-ci issues**
Already solved many, will look out for relevant and solve them.
 **why is track heading red? It should not be.**
Its the track color choosen by the organiser. Each Track color is like that.
 **first text line next to picture is not properly aligned**
Will correct that.

**Comment by mariobehling** [comment]
Track color should be reflected in > time field < not in heading.

Please read the issue carefully. It seems a lot of discussion just happens because devs do not read the issue properly.

**Comment by championswimmer** [comment]
@aayusharora you'll have to redo the PR as I have de-nested the app structured 

as discussed with @mariobehling I have merged the de-nesting PR myself only.

**Comment by aayusharora** [comment]
Ok @championswimmer then redoing this PR.

**Pull request closed without merging**
