### PR TITLE
Fixes#1610 Changes Fossasia samples to FOSSASIA Summit

### LINKED ISSUE #1610: Change Fossasia samples to FOSSASIA Summit
The Fossasia samples and overview page should use FOSSASIA Summit as text.

### PR DESCRIPTION
**Pull request by ParthS007**
Fixes #1610 

Changes: 
https://parths007.github.io/fossasia11/

### CODE REVIEW

**Comment by ParthS007** [comment]
@geekyd Please merge this. Thanks

**Comment by mariobehling** [comment]
Looks like you did not change this in the sample files here https://github.com/fossasia/open-event.

It needs to be fixed in the original source.

**Comment by mariobehling** [comment]
Please check this as well https://github.com/fossasia/open-event-webapp/issues/1625

**Comment by geekyd** [comment]
@ParthS007 Please resolve the conflicts.

**Comment by ParthS007** [comment]
@geekyd Please review https://github.com/fossasia/open-event/pull/257 , after that only I will able to update this PR

**Comment by ParthS007** [comment]
opening a new PR 👍

**Pull request closed without merging**
