### PR TITLE
Fixes the Track name list position issue

### LINKED ISSUE #1423: Track Name List gone down to the bottom on the tracks page
After some recent changes made, the track name list has again gone down to the bottom of the page. This is an issue which keeps appearing again. Here is the screenshot

screenshot from 2017-07-28 19-45-27
screenshot from 2017-07-28 19-45-20

This time, I will try to fix the issue and write tests for it so it doesn't appear again. Sorry!

### PR DESCRIPTION
**Pull request by Princu7**
Fixes #1423 

**Changes**
* The track name list is now visible near the top of the page. Earlier, it went down to the bottom of the tracks page
* To make sure this issue doesn't ever happen again, added selenium tests for it
* Also, corrected some of the bookmark tests which were written in a slightly wrong manner and were failing after making the above changes

**Test Server**
http://secure-meadow-20680.herokuapp.com

**Video for Demonstration**
https://saucelabs.com/beta/tests/5e059ace942f4e0694ca8cf23654079e/watch#517

**Test Website**
https://princu7.github.io/websiteTest/index.html

@aayusharora @geekyd @sumedh123 Please review. Thanks :)

### CODE REVIEW

**Comment by Princu7** [comment]
Some Screenshots. The track name list is visible on the front of the page. Also, the date tab and the session content below are horizontally aligned.

* Schedule Page
screenshot from 2017-07-29 13-48-12
* Rooms Page
screenshot from 2017-07-29 13-48-33
* Tracks Page
screenshot from 2017-07-29 13-48-24

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by Princu7** [comment]
@mariobehling @geekyd Resolved conflicts. Please review again. Thanks!

**Comment by mariobehling** [comment]
Thanks. I wonder when you are following up on the new features and high priority issues, e.g. https://github.com/fossasia/open-event-webapp/issues/1317

Please focus now to get this system up to industry standard.

**Comment by Princu7** [comment]
@mariobehling Yes. I have already started working on that issue. Will try to complete it as soon as possible.

**Pull request merged**
