### PR TITLE
Fixes colour of links on speakers page

### LINKED ISSUE #1069: Design issue of icons and speaker images
There are a number of issues with the design, that were solved before and were changed (I do not see who changed it in which PR).

* [ ] Scroll over on social icons on speaker images makes the icons red. It should not make them red.
* [ ] Some pictures of speakers in tracks do not display properly
screenshot from 2017-02-23 19-58-06

### PR DESCRIPTION
**Pull request by CosmicCoder96**
fixes #1069 

giphy 1

As for the speaker images, I was unable to reproduce the issue and tested various speakers on different screen sizes.
@mariobehling Can you give a specific instance where this occurred.

### CODE REVIEW

**Comment by Princu7** [comment]
@CosmicCoder96 Please try to generate the event site using this API endpoint of open-event-orga-server:
`https://eventyay.com/api/v1/events/6`
Thanks for the request !!

**Comment by CosmicCoder96** [comment]
@princu7 
Thanks for the info. I will look into it.

**Comment by CosmicCoder96** [comment]
@aayusharora @princu7 it appears the fields have changed and using the API end point crashes the app as of now. 
There should be an additional issue to fix this.

**Comment by Princu7** [comment]
@CosmicCoder96 Hi. I am not sure that I get you. I tried it on the official deployed app on Heroku and it seems to work. Are you sure that you used this API end-point : `https://eventyay.com/api/v1/events/6`?
Please check again. Thanks!!

**Comment by geekyd** [comment]
@CosmicCoder96 We need to handle the case where the `"session_type" = null` to do so please apply a check and if the data is null simple add `&nbsp;`that would make the images consistent and solve the bug.

**Comment by CosmicCoder96** [comment]
@Princu7  The app failed on my local machine but succesfully deployed on heroku, maybe a networking issue. I have now made the required changes. Also I noticed there was a bug in the fold.js file 

const roomName = (session.microlocation == null) ? ' ' : session.microlocation.name;
const session_type = (session.session_type == null) ? ' ' : session.session_type.name ;

In both the cases , when the value was null the empty space between the single quotes prevented the handlebar template from perceiving the value as null. I have fixed that and the speaker icons work now. 
Please review again.

**Comment by aayusharora** [comment]
Thanks @CosmicCoder96

**Pull request merged**
