### PR TITLE
solution for the issue while running npm run start

### PR DESCRIPTION
**Pull request by dexta11**
Fixes #[Add issue number here. Note: This will automatically close the issue. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Updation of the INSTALLATION_LOCAL.md

Changes: [Add here what changes were made in this issue and if possible provide links.]

Screenshots for the change:

### CODE REVIEW

**Comment by Princu7** [comment]
@dexta11 Thanks for the request. Please remove the swap files and squash your commits and give an accurate description of the task which is being done in this pull request. Try to fill in the template details provided on the issue. Thanks!!

**Comment by geekyd** [comment]
@dexta11 Please remove the redundant swap file and squash your commits. Thanks

**Comment by mariobehling** [comment]
Which issue is this related to? Please help to keep everyone on board and follow our best practices.

**Comment by dexta11** [comment]
@Princu7 sorry for the delay as my exams are going on so not able to pay attention towards it. i will definitely remove the swap file and will give details.
@geekyd i will do the needful.
@mariobehling actually i was getting an error while i was installing open-event-webapp on local machine so, previously i have raised an issue and created a PR since there was some mistake i got some comments on that . So i have reconsidered the steps in the installation document and wrote it more precisely without creating any confusion.

**Comment by aayusharora** [comment]
@dexta11 Which previous issue you are talking about? Can you mention the issue number in the description above.

**Comment by dexta11** [comment]
@aayusharora issue #6

**Comment by aayusharora** [comment]
@dexta11 The issue was closed in 2015. It does not require a PR. It is clearly written `championswimmer closed this on Jun 3, 2015` 
Hence, closing this.

**Pull request closed without merging**
