### PR TITLE
Improved Search Box UI

### PR DESCRIPTION
**Pull request by Lplenka**
Fixes #[1329]

Changes: Changed the Search Box UI

Before Changes:
[https://demolp.github.io/OSCAL_2017/](https://demolp.github.io/OSCAL_2017/)
Website After Changes:
[https://demolp.github.io/OSCAL2017new/schedule.html](https://demolp.github.io/OSCAL2017new/schedule.html)

### CODE REVIEW

**Comment by Princu7** [comment]
@lplenka Solid work. The new search bar looks beautiful :grinning: . Everything is good on the tracks and rooms pages but there are some problems with the layout on the schedule page though. The starred button is elongated on the standard size and on some screen sizes, the search bar is shifted by a good margin.

Please do two more changes:
* Remove property `flex-grow` completely from both search bar and starred button on the schedule page.
* Make `padding-left: 0` on the search-bar.
Please test the above changes and see if they improve the UI. If you have more ideas, please go ahead. Thanks!!

**Comment by Lplenka** [comment]
@Princu7 I think removing the flex-grow property of only search bar does the right thing. Please verify using Chrome dev tools.

**Comment by Princu7** [comment]
@lplenka Okay. If I am doing it correctly, then after removing the flex-grow on the search bar, it looks like
 this:
screenshot from 2017-06-11 19-06-00
The starred button is elongated and it doesn't look good on bigger screen.

If we remove flex-grow from the starred button too and make padding-left: 0 on the search bar, it looks like this:

screenshot from 2017-06-11 19-07-01
It looks more concise and compact and is in line with the current look of the site. It also behaves better on changing screen size.

Please check. And If I did something wrong or made a mistake, then please correct me :grinning: Thanks!!

**Comment by Lplenka** [comment]
Okay, let me check

**Comment by Lplenka** [comment]
Looks Fine, Adding the changes :smile:

**Comment by Princu7** [comment]
@lplenka Looks good to me. Please change 'Fixes #[1329]' to 'Fixes #1329' so that the corresponding issue get closed automatically when the PR is merged. Thanks!!

**Pull request merged**
