### PR TITLE
Fixes#1609 #1608 Removes unwanted effects and design

### LINKED ISSUE #1608: Confusing effect of whole page image when cursor off-page
I cannot find where this contribution was merged, but showcasing the app today resulted in a complete confusion of users. The App was very simple until recently. Somehow unnecessary UI elements were merged.

Please take out the effect to show an image over the whole page when the cursor is off-page.

screenshot from 2018-01-08 19-36-30

### LINKED ISSUE #1609: Top right menu does not always load and has unwanted effects / design
The top right dropdown menu box is slow. It seems to have a delay and has a kind of white shadow. It should be much simpler - actually it should be like it was before. Simple and super fast.

screenshot from 2018-01-08 19-40-43

### PR DESCRIPTION
**Pull request by ParthS007**
Fixes #1609 
Fixes #1608 

Changes: https://murmuring-basin-58897.herokuapp.com/

image

### CODE REVIEW

**Comment by geekyd** [comment]
@ParthS007 Decrease the opacity of shadow. Make it look like https://badgeyay-dev.herokuapp.com/. Follow the same for the the menu

**Comment by ParthS007** [comment]
@geekyd Why `open-event-web app` is still on `http`?

**Comment by geekyd** [comment]
@ParthS007 It is not updated. @mariobehling Can you please update it?

**Comment by ParthS007** [comment]
@mariobehling  @geekyd  Please review

**Comment by geekyd** [comment]
Looks good! Merging it for now, we can iterate from here.

**Pull request merged**
