### PR TITLE
Milestone2 Theme added

### PR DESCRIPTION
**Pull request by aayusharora**
**Live Version** http://translator-albert-75345.bitballoon.com/#/speakers

### CODE REVIEW

**Comment by aayusharora** [comment]
@juslee , You can merge it .

**Comment by championswimmer** [comment]
There is a minor font issue 
```
downloadable font: download failed (font-family: "Glyphicons Halflings" style:normal weight:normal stretch:normal src index:1): bad URI or cross-site access not allowed source: http://d33wubrfki0l68.cloudfront.net/css/e9f8121ff973fe1b1a0f032d6118e2c7f463b4cc/fonts/glyphicons-halflings-regular.woff2
```

**Comment by championswimmer** [comment]
@aayusharora also any idea why the session are not showing up ?

**Comment by aayusharora** [comment]
@championswimmer  , locally its working correct , font is failing saying the Cross domain request . I will do it .

**Comment by championswimmer** [comment]
Cool. merging this

**Pull request merged**
