### PR TITLE
[WIP]Fixes#1512 Fix Travis

### LINKED ISSUE #1512: Fix travis for the application
**Actual Behaviour**
The travis build is failing for each PR. Please check https://travis-ci.org/fossasia/open-event-webapp/builds/290453248?utm_source=github_status&utm_medium=notification

**Expected Behaviour**
The travis must pass for each build.

This is a known issue in travis :
```
No output has been received in the last 10m0s,
this potentially indicates a stalled build or something wrong with the build itself.
```

### PR DESCRIPTION
**Pull request by ParthS007**
Fixes #1512 

Changes:
-  Fix Travis

### CODE REVIEW

**Comment by ParthS007** [comment]
@agbilotia1998 I think RedHat sample is creating the problem.

**Comment by agbilotia1998** [comment]
@ParthS007 I have opened a pull request as soon as it gets merged travis would generate redhat sample.

**Comment by ParthS007** [comment]
Ok @agbilotia1998 👍

**Comment by geekyd** [comment]
Closing this,
Issue was resolved in #1551

**Pull request closed without merging**
