### PR TITLE
#1231 : fix the disalignment and missing spaces

### LINKED ISSUE #1231: Recent changes resulted in missing spaces and disalignment
E.g. 

* [x] sidebar tracks are disaligned and do not have a space next to dots.

screenshot from 2017-04-25 12-51-31

* [x] Dates and other buttons have different distance and are disaligned.

screenshot from 2017-04-25 12-57-02

* [ ] New colors that don't follow previous design have been introduced and buttons are not separated.

screenshot from 2017-04-25 12-57-57

* [x] Schedule page sessions don't have space between them
screenshot from 2017-04-25 13-09-18

### PR DESCRIPTION
**Pull request by sumedh123**
Fixes #1231 . @mariobehling Please review.

Screenshots for change : 
Previous : 
previous
After : 
afterfix
Pills : 
pills
Buttons : 
buttons

### CODE REVIEW

**Comment by aayusharora** [comment]
We do not have testing on frontend side. Please provide a hosted version of this site. @sumedh123

**Comment by aayusharora** [comment]
Also @sumedh123 the button background-color is blue when it is active. Please change it and match the design.

**Comment by aayusharora** [comment]
@sumedh For faster progress on Issues I am merging this. Please fix the button color in the other PR. Good work.

**Comment by aayusharora** [comment]
@sumedh For faster progress on Issues I am merging this. Please fix the button color in the other PR. Good work.

**Comment by sumedh123** [comment]
@aayusharora Sorry for the delay. I was busy in exams. Surely I willfix it in my next PR.

**Comment by mariobehling** [comment]
* [ ] Dates and other buttons still disaligned. They are not in the same exact row.

screenshot from 2017-04-25 12-57-02

**Comment by sumedh123** [comment]
@mariobehling I am on it.

**Pull request merged**
