### PR TITLE
Supports Old APIs

### PR DESCRIPTION
**Pull request by agbilotia1998**
Provides support to Old APIs

### CODE REVIEW

**Comment by agbilotia1998** [comment]
@mariobehling please review.You need to force push these commits as the branch api_v1 is in sync to new type API.

**Comment by ParthS007** [comment]
@agbilotia1998  why there are conflicts ? Are they intentional ?

**Comment by agbilotia1998** [comment]
@ParthS007 the conflicts are because the branch api_v1 is in sync with the latest API.

**Comment by mariobehling** [comment]
@ParthS007 If this is ok, could you please merge it? I am having limited time to go through all of it. I trust you guys to move this forward. :-)

**Comment by mariobehling** [comment]
Even though the changes are approved by you guys, I am puzzled by this PR. It has a lot of former commits of other people and lots of merge conflicts. That would actually mean that other issues that are solved come back or not?

In any case, if you think this will bring us forward and help to get the support for the old API back, please merge this now.

**Comment by agbilotia1998** [comment]
@mariobehling I don't have write access to this repository, and these commits need to be force pushed.@parths007 can you pull these commits and force push on api_v1 branch.

**Comment by mariobehling** [comment]
@agbilotia1998 Ok, I gave you temporary write access. Please use wisely. Thank you! :+1:

**Pull request merged**
