### PR TITLE
add logo

### PR DESCRIPTION
**Pull request by nolik2000**

### CODE REVIEW

**Comment by jig08** [comment]
@nolik2000 There isn't any file changed. Kindly see to it.

**Comment by nolik2000** [comment]
can you say where I have add logo (which file)?

**Comment by mananwason** [comment]
@nolik2000 You have reverted your commit. Please check

**Comment by nolik2000** [comment]
I also done It bit it doesn't help(

**Comment by nolik2000** [comment]
I also done it but it doen't help(

**Pull request closed without merging**
