### PR TITLE
Revert "radio-button-labels-clickable"

### PR DESCRIPTION
**Pull request by agbilotia1998**
Reverts fossasia/open-event-webapp#1537
-> The menus for uploading jsons and entering url are not getting displayed.

### CODE REVIEW

**Comment by himanish-star** [comment]
@agbilotia1998 , This error is not due to my PR. You can revert and check that the errors will persist. It is due to another merged branch

**Comment by himanish-star** [comment]
@agbilotia1998 , the error is related to sockets

**Comment by himanish-star** [comment]
@agbilotia1998 , now checkout https://mighty-fjord-71199.herokuapp.com/

I have made the changes sorry on my part again. I'll file a PR soon

**Comment by agbilotia1998** [comment]
It is fixed in #1562 that is why I am closing it.

**Pull request closed without merging**
