### PR TITLE
Fixes #1569: Improvised

### LINKED ISSUE #1569: Dull
**Actual Behaviour**
The web app page is very dull
**Expected Behaviour**
Make it a bit more appealing
**Steps to reproduce it**
Add a background image
**Would you like to work on the issue?**
Yes! Pls don't work on it without my consent

### PR DESCRIPTION
**Pull request by samyakbvs**
Fixes #1569 

Changes: A Hover effect and light background image

Screenshots for the change:

### CODE REVIEW

**Comment by samyakbvs** [comment]
They are resolved

**Comment by samyakbvs** [comment]
screen shot 2017-12-25 at 1 26 57 pm

screen shot 2017-12-25 at 1 26 54 pm

**Comment by samyakbvs** [comment]
You hover over the 'Web application' image and the form appears

**Comment by samyakbvs** [comment]
I won't be able to squash the commits

**Comment by samyakbvs** [comment]
I can't and I have genuine reason for that

**Comment by samyakbvs** [comment]
screen shot 2017-12-25 at 10 20 51 pm
Till here it is my test link but...
screen shot 2017-12-25 at 10 21 00 pm
As soon as I click on web event generator it goes to the original site instead of my test link

**Comment by samyakbvs** [comment]
@ParthS007

**Comment by samyakbvs** [comment]
https://samyakbvs.github.io/samyakjwefwbvsain-open-event-webapp/

**Comment by aayusharora** [comment]
I can't see these changes here https://samyakbvs.github.io/samyakjwefwbvsain-open-event-webapp/ @samyakbvs

**Comment by samyakbvs** [comment]
I know but how do I restrict the site from changing when I click in the navbar?

**Comment by samyakbvs** [comment]
Opening a new one

**Pull request closed without merging**
