### PR TITLE
Added track name list to the sidebar on smaller screens for filtering sessions

### PR DESCRIPTION
**Pull request by Princu7**
Partially Fixes the issue #1317 

Changes:
* Adds mobile view of the track name list for filtering sessions

**Test Server**
http://secure-meadow-20680.herokuapp.com

**Demo Website**
http://princu7.github.io/websiteTest

@aayusharora @geekyd @sumedh123 @harshitagupta30 Please review. Thanks :)

### CODE REVIEW

**Comment by Princu7** [comment]
Here are some of the screenshots
screenshot from 2017-08-04 10-32-41
screenshot from 2017-08-04 10-32-36

@aayusharora @geekyd @sumedh123 @harshitagupta30 Please review. Thanks :)

**Comment by geekyd** [comment]
@Princu7 Great work! Can we hide the side menu when the user clicks on the track titles?
It will improve the UX. What do you think?

**Comment by sumedh123** [comment]
@Princu7 Also one more suggestion, can we blur the other part of the screen when the side bar is active? Or this can be done in other separate issue also.

**Comment by Princu7** [comment]
@sumedh123 Thanks for the suggestion. Yes, we should do it in a separate issue later when major issues are resolved. That would be more apt I guess. @geekyd Yes, that is a good option. I will try to change to it. Thanks!

**Comment by Princu7** [comment]
Made the suggested changes @geekyd Here is the test server link. Now on clicking the name of the track in the sidebar will close it. 

**Test Server**
http://secure-meadow-20680.herokuapp.com

**Test Site**
http://princu7.github.io/websiteTest

**Pull request merged**
