### PR TITLE
Add tracks legend to the schedule page

### LINKED ISSUE #775: Add tracks legend to Schedule page
Add tracks legend to Schedule page - similar to the Rooms page

### PR DESCRIPTION
**Pull request by alexagr**
resolves #775

### CODE REVIEW

**Comment by mariobehling** [comment]
Please check the travis build is failing. Thank you.

**Comment by alexagr** [comment]
First of all - it has nothing to do with my delivery.
But I looked into Travis logs anyway - and it looks like someone broke the JSON files that we are using for testing. Specifically the test fails while parsing https://raw.githubusercontent.com/fossasia/open-event/master/sample/FOSSASIA16/speakers - JSON parser throws SyntaxError.

If I load the URL to https://jsonformatter.curiousconcept.com/ I see that the syntax is in fact broken - e.g. at line 1582 the comma is missing after facebook URL:

```
    {
        "id": 65, 
        "name": "Sahil Bajaj", 
        "email": "sahil_bajaj@fossasia.org", 
        "mobile": null, 
        "photo": "/images/speakers/SahilBajaj_65.jpg", 
        "organisation": "GitHub/Homebrew/Grumpy Gits", 
        "position": null, 
        "country": "Scotland", 
        "short_biography": "", 
        "long_biography": "Sahil is a developer based in Singapore.", 
        "website": "http://mikemcquaid.com", 
        "twitter": "https://twitter.com/MikeMcQuaid", 
        "facebook": "https://www.facebook.com/sahil2912" 
        "linkedin": "", 
        "sessions": [
            {
                "id": 87, 
                "title": "GitHub Workshop"
            }
        ]
    }, 

```

Any idea on where these JSONs come from and who can re-generate them?

**Comment by the-dagger** [comment]
@alexagr the json that we use can be found in [github.com/fossasia/open-event](github.com/fossasia/open-event), so have a look there and send a PR if any of the json you find is broken.

**Comment by alexagr** [comment]
@the-dagger just issued PR for open-event - please merge

**Comment by the-dagger** [comment]
Merged.

**Comment by alexagr** [comment]
looks like all is good now

**Comment by mariobehling** [comment]
@alexagr Yes, you are right. Thanks for the fixes. Though I do not exactly understand why it did not work. The missing comma was there for some time and it worked before. I also re-added the photo you took out now and it is also working. Thanks for looking into those details!

**Comment by alexagr** [comment]
Both bugs were introduced by commit #340b25 on September 1.
It removed the comma after "facebook" element for "Mike McQuaid, Sahil Bajaj" (id=65) and removed "photo" element for "Herr Flupke" (id=155).

**Comment by mariobehling** [comment]
@alexagr Thanks, fixed it. Herr Flupke is back :-) http://fossasia.github.io/open-event-webapp/speakers.html

**Pull request merged**
