### PR TITLE
Fixes #1663 Enhances #1641 : Created Docker Installation from Scratch , Enhanced GOOGLE Deploy Doc

### LINKED ISSUE #1663: Add Docker Installation Procedure
**Actual Behaviour**

No such documentation exists, anywhere !

**Expected Behaviour**

It should !

**Would you like to work on the issue?**

**Just firing the PR!**

### PR DESCRIPTION
**Pull request by 0x48piraj**
# Fixes #1663
# Enhances #1641

Changes: 
- **_Added INSTALLATION Procedure for Docker_** !! *(I literally created this)*
- Embedded ASCII Cast of Complete Process

Screenshots for the change: 

image

---

image

### CODE REVIEW

**Comment by 0x48piraj** [comment]
Ping @geekyd :+1:

**Comment by 0x48piraj** [comment]
@fossasia/open-event-core @fossasia/open-event-web-app @fossasia/open-event-web-app-admin

**Comment by geekyd** [comment]
@0x48piraj Share the link of the docker deployment.

**Comment by 0x48piraj** [comment]
I don't filmed it. I'll add at after GCI, is it Ok?

**Comment by geekyd** [comment]
@0x48piraj Provide the deployment link of docker deployed using the provided docs.

**Comment by agbilotia1998** [comment]
@0x48piraj any updates?

**Comment by 0x48piraj** [comment]
Yeah, Waiting for a merge 😄

**Comment by agbilotia1998** [comment]
@0x48piraj you were asked for the deployment link by @geekyd .

**Comment by 0x48piraj** [comment]
Document files need not to have a "deployment link"

**Comment by agbilotia1998** [comment]
I guess you missed this comment "@0x48piraj Provide the deployment link of docker deployed using the provided docs."

**Comment by 0x48piraj** [comment]
It will be good if someone like you can test the documentation and give suggestion.

**Pull request merged**
