### PR TITLE
reduce size of star button(#1780)

### LINKED ISSUE #1780: Reduce size of Star button
The star button has a different size than the left-hand buttons. Please help and reduce the size and match the design of the other buttons on the left.

screenshot from 2018-03-18 13-56-30

### PR DESCRIPTION
**Pull request by AdityaHirapara**
#### Short description of what this resolves:
Reduce size of star button and make design of that button same as other buttons on page.

Fixes #1780.

Deployment link (of preview) : https://openeventwebapp.herokuapp.com/live/preview/an@gmail.com/FOSSASIASummit2017/index.html

### CODE REVIEW

**Comment by mariobehling** [comment]
Deployment link not working. You need to deploy it to gh-pages for example.

**Comment by AdityaHirapara** [comment]
Deployment link on gh-pages : https://adityahirapara.github.io/eventSiteWebApp/
Sorry for a late reply...

**Comment by AdityaHirapara** [comment]
@agbilotia1998 , I have pushed the changes, please review.

**Comment by AdityaHirapara** [comment]
Ya...I have updated

**Comment by AdityaHirapara** [comment]
I think Its due to cached webpage... Did you try after unregister service worker?  Bcoz I was facing same problem at time of debugging.

**Comment by agbilotia1998** [comment]
@AdityaHirapara yes there was an issue with service workers.Thanks for the PR :)

**Pull request merged**
