### PR TITLE
i have added logo to the title bar

### PR DESCRIPTION
**Pull request by rohythakur**
ii have added logo to the title bar as suggested at
https://codein.withgoogle.com/dashboard/task-instances/6222480846880768/?sp-page=1

### CODE REVIEW

**Comment by SaptakS** [comment]
@championswimmer I guess this PR is good to be merged?

**Comment by mananwason** [comment]
@rohythakur Please squash commits. You can find instructions to squashing here https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md

**Comment by rohythakur** [comment]
@mananwason  I cannot squash both commits as second one is not necessary and I think it's also somehow solved earlier in other pull request to I have to delete it

**Comment by mananwason** [comment]
Go ahead then, Delete it please.

**Pull request closed without merging**
