### PR TITLE
Width of map and contact details changed

### PR DESCRIPTION
**Pull request by magician03**
Changed the width of map to col-md-8 and contact details to col-md-4,  looks more clean than earlier, there is a lot a whitespace towards the right of contact details unused.

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you. Please provide a link to a sample page on your own github pages repo for testing.

**Comment by magician03** [comment]
Thanks for quick response, here is the Github pages link
<https://magician03.github.io/open-event-webapp/> you've asked for. Notice
the map section, there is lot of blank space left over there earlier.

**Comment by magician03** [comment]
In addition to my previous mail,

There were some unsafe-script issues on loading it via HTTPS, please load
the Github Pages site <http://magician03.github.io/open-event-webapp/> over
HTTP to view the map section.

Cheers,
magician03

**Comment by mariobehling** [comment]
Thank you. Looks good. Usually we work in the way, that people create an issue and match a PR with an issue. This allows others to give input before a PR is made and avoid wasting devs time. Let's follow this in future, ok?

This is just a small task here. As you are working on it, could you please decrease the height of the map area. I do not think such a big height is needed. Cheers.

**Comment by magician03** [comment]
Yeah sure :), Right now it is given 600 px, I am thinking of changing it to 75vh to make it more responsive, 75vh because, in mobile view the contact details could be rendered in the rest 25vh .

Whats your opinion ?

**Pull request closed without merging**
