### PR TITLE
Send correct event folder link and a message to inform user in the mail when the cloud upload fails

### LINKED ISSUE #1452: Mail send with a wrong download link to the user when the cloud upload of the event folder fails
I mentioned this on this [PR](https://github.com/fossasia/open-event-webapp/pull/1451)  but opening a new issue for it now. This is the workflow-
* We generate the event folder and then upload to the cloud storage and get the URL of the uploaded folder.
* We then mail the user about the generated event which also contains a link to the uploaded event folder.

The question is what should we do when the upload to the cloud upload fails? Directly sending the mail to the user does not make sense since the download location of the uploaded event folder will be null.

So, we have two options maybe:-

* Don't send a mail to the user if the cloud upload fails.
* Send a different email telling that the cloud upload has failed and present the user the download link of the event folder currently present on the Heroku app itself along with the warning that it will expire within few hours.

Thoughts @aayusharora @geekyd @harshitagupta30 @agbilotia1998

### PR DESCRIPTION
**Pull request by Princu7**
Fixes #1452 

**Changes**:
* Send correct event folder link and a message to inform the user in the mail when the cloud upload fails. The user will receive the email containing the download link of the event folder on the Heroku itself along with the message that the zip will be purged within few hours and to download it immediately.

Screenshots for the change: 
screenshot from 2017-08-22 23-46-44

**Test Server**
http://peaceful-meadow-19050.herokuapp.com

@aayusharora @geekyd @sumedh123 @harshitagupta30 Please review. Thanks :)

### CODE REVIEW

**Comment by Princu7** [comment]
The code coverage tests are failing because there are no sendgrid keys for sending the mail and no aws keys for uploading the event folder. That's why there are misses. I have added Sendgrid key on the test server and the mail is delivered along with the caution message to warn the user to download the folder immediately otherwise since it would be purged from the generator server.

**Comment by Princu7** [comment]
@mariobehling Thanks for reviewing. Here is the download part when the cloud upload of the event fails

> You can download a zip of your website from here. The download link for zip expires on Thursday, August 24th 2017. There was some problem with the cloud upload of the event folder. Please download the zip immediately. It will be purged soon from the generator server

**Comment by Princu7** [comment]
@mariobehling I updated the PR. This is the success message when the upload of the event folder takes place successfully.

> Hi ! 
> Your webapp has been generated 
> You can preview it live on link. This link expires on Friday, 10 AM
> You can download a zip of your website from here. The download link for zip expires on Monday, August 28th 2017
> 
> Thank you for using Open Event Webapp Generator :)

And this is the error message when the upload fails

> Hi ! 
> The cloud upload of the webapp failed. Please inform us about it on our `chat channel `or file an issue on our `Github repo`

Both the `chat channel` and the `Github Repo` are clickable which will take the user to appropriate location.

**Test Server**
https://peaceful-earth-19050.herokuapp.com/

**Comment by Princu7** [comment]
The CI tests will fail because of the inconsistencies in the samples and will be fixed after all the included samples in the showcase site are updated to the new attributes. But, the process of the generation of the events are working and can be checked on the test server mentioned here.
https://peaceful-earth-19050.herokuapp.com/

**Comment by mariobehling** [comment]
Ok, thanks.

**Pull request merged**
