### PR TITLE
Show all sessions on all the three pages: rooms, tracks and schedule

### LINKED ISSUE #1327: Show complete schedule without filters (for all days) on start page of schedule/tracks/rooms page
Opening the app now shows only the schedule for the first days. There is a filter set, that results in the display of the first day only. Only show days for one day once a filter has been set - meaning when the user clicked on a specific day.

Ensure the same implementation on the pages
* Schedule
* Rooms
* Tracks

Compare: https://fossasia.github.io/open-event-webapp/schedule.html

### PR DESCRIPTION
**Pull request by Princu7**
Fixes #1327 

Changes:
* All the sessions from all the days are displayed on the three pages (tracks, rooms, and schedule) now.

**Test Link**
https://princu7.github.io/websiteTest
@aayusharora @geekyd Please review. Thanks!

### CODE REVIEW

**Comment by geekyd** [comment]
@Princu7 I'm not sure if this is the desired behaviour specified in the issue description. I think the desired behavious is:
- Each page shows all the sessions when there is no filter applied(no specific date button is clicked)
- When a specific date is clicked we show the sessions only for that date.

@mariobehling Please guide. Thanks

**Comment by Princu7** [comment]
@geeekyd Oh. Sorry for the misunderstanding. I will correct the mistake. Thanks!!

**Comment by Princu7** [comment]
@geekyd Updated the link. Please review again. Thanks!!

**Comment by mariobehling** [comment]
Thanks.

**Pull request merged**
