### PR TITLE
scrollbar radius and color changed

### LINKED ISSUE #1902: customize scrollbar
**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by shubham3211**
Fixes #1902 
Sample:-https://shubham3211.github.io/fb-scroll/
fb-scroll

### CODE REVIEW

**Comment by agbilotia1998** [comment]
@shubham3211 is the preview link updated?

**Comment by shubham3211** [comment]
@agbilotia1998 Yes.

**Comment by agbilotia1998** [comment]
@shubham3211 I found no change in the scrollbar
Screenshot: 
screenshot from 2018-06-02 12-02-14

**Comment by agbilotia1998** [comment]
Okay, I tested in firefox only. Thanks.

**Pull request merged**
