### PR TITLE
Supports Old APIs.

### LINKED ISSUE #1468: Autogeneration from API not working
There is an organizer who tries to generate an app with the API https://eventyay.com/api/v1/events/257 on https://webgen.eventyay.com/

The generation stops at 50% on http://opev-webgen-dev.herokuapp.com/

### PR DESCRIPTION
**Pull request by agbilotia1998**
Fixes #1468.
Changes added support for old APIs by reverting back to previous commit supporting old APIs.

### CODE REVIEW

**Comment by agbilotia1998** [comment]
@geekyd please review.

**Comment by geekyd** [comment]
@agbilotia1998 Also clear the history it seems like many commits have already been merged to the development branch.

**Comment by agbilotia1998** [comment]
@isuruAb this needs to be force merged as api_v1 branch is a copy of development branch which supports new APIs and reverting back to previous commits is creating conflicts.
 @geekyd all the commits in this new branch would be same except the commits which changed the support from old APIs to the new one.

**Comment by agbilotia1998** [comment]
https://github.com/fossasia/open-event-webapp/commit/c791f4771a290819ab8fb991b045c879e9b118b2 
@geekyd this is the commit adding support to new APIs.
Deployment link is : https://openeveweb.herokuapp.com/

**Comment by niranjan94** [comment]
@geekyd @agbilotia1998 can't we just reset the `api_v1` to one of the older commits ?

**Comment by geekyd** [comment]
@niranjan94 Resetting will work, as long as we do not intend to have the latest changes. I think we can either :
- Delete the commit that makes the changes and force push
- Add a commit to revert the changes
- Simply reset to older commit

I think we should either go with 1 or 2 if we want the latest changes, if the changes are not important we can go ahead and simply reset the branch.

**Comment by agbilotia1998** [comment]
@geekyd @niranjan94 this PR is intended to implement the first suggestion.Please check the commits and also test the deployment link.

**Comment by agbilotia1998** [comment]
@geekyd @niranjan94 please review.

**Comment by geekyd** [comment]
@niranjan94 What approach should we take here? Please help

**Comment by niranjan94** [comment]
We'll go with `Delete the commit that makes the changes and force push`

**Comment by agbilotia1998** [comment]
@niranjan94 @geekyd this implementation is done with this PR.Please check out out the deployment link with old APIs and the commit sequence.

**Comment by geekyd** [comment]
@niranjan94 How should we proceed here.I think you can delete the commit in the `api_v1` branch or we can go ahead and merge this PR. What do you suggest?

**Comment by agbilotia1998** [comment]
@geekyd directly deleting commit was creating conflicts that is why I opened this PR. The deployment link is working fine for  https://eventyay.com/api/v1/events/257 which is based on old APIs please check.

**Comment by geekyd** [comment]
@agbilotia1998 I have already checked that, it is working. Lets wait for @niranjan94's reply.

**Comment by agbilotia1998** [comment]
@geekyd @niranjan94 @mariobehling any changes required in this PR?

**Comment by mariobehling** [comment]
@agbilotia1998 Thanks. Please resolve conflicts and we can add it.

**Comment by mariobehling** [comment]
@agbilotia1998 Please resubmit these changes with a clean PR.

**Pull request closed without merging**
