### PR TITLE
Added test for download dropdown on schedule page

### LINKED ISSUE #1614: Add more Selenium tests
Add more tests for schedule, tracks, rooms & speakers page. 

- [ ] Add tests for sessions on each page check speaker, type of session, background color etc.
- [ ] Add tests for social links (Tests for Buttons already exist) also add test to check url for sharing next to social buttons.
- [ ] Add test for download dropdown on schedule page.
- [ ] Add tests for speakers page for hover state.
- [ ] Add tests for social links on the top bar & footer
- [ ] Add tests for tracks name
- [ ] Add tests for sponsors on event page.

@agbilotia1998 @ParthS007 Have a look at this, add more if I missed something.

### PR DESCRIPTION
**Pull request by agbilotia1998**
Partially Fixes #1614

### CODE REVIEW

**Comment by agbilotia1998** [comment]
@geekyd please review!

**Comment by agbilotia1998** [comment]
@geekyd I have added test for visibility of dropdown menu only where download button appears.Should I add more to check if download starts or not?

**Comment by geekyd** [comment]
@agbilotia1998 Yes

**Comment by agbilotia1998** [comment]
@geekyd this test is working fine on my chromedriver but travis fails at this.Can you help me debug this?

**Comment by agbilotia1998** [comment]
@geekyd this test is working fine on my chromedriver but travis fails at this.Can you help me debug this? Or if possible can you please share travis shoot of this build with me?

**Comment by agbilotia1998** [comment]
@geekyd the problem is that we are running tests on linux env. whereas the saucelabs use windows for chromedriver therefore I am not able to check download of files.The files are getting downloads but the path is not been read.

**Comment by geekyd** [comment]
@agbilotia1998 For now lets add the tests to check dropdowns. We will add tests for download later.

**Comment by agbilotia1998** [comment]
@geekyd done please review.

**Comment by geekyd** [comment]
@agbilotia1998 Fix codacy issues. Thanks.

**Pull request merged**
