### PR TITLE
Enable Sauce Connect on Pull Requests

### LINKED ISSUE #1307: Enable Sauce Connect on Pull Requests
There have been some problems with connection to Sauce Cloud on Pull Requests. I will try to explain the problem step by step:
* Travis doesn't support Selenium natively, so we have to run it on Sauce Labs which provides its services free for open source project.
* To be able to connect to Sauce Cloud remotely through Travis, we need `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY`. 
* The access key should be kept safe and hence, it is often made into a private environment variable.
* Travis doesn't import private variables during the pull request builds for security reasons.

In order to find a workaround this problem, we have to enable `JWT` addon and encrypt the variable using it. More information regarding its working is explained in the official docs:
https://docs.travis-ci.com/user/jwt

I have started the work and will send a PR soon. Thanks!!

### PR DESCRIPTION
**Pull request by Princu7**
Fixes #1307

Changes: 
* Enables connection to Sauce Connect on Pull Requests. This is done with the help of `JWT` add-on which replaces encrypted variables with time-limited authentication token which is exposed to pull requests without security consequences. Read more about it here:
https://docs.travis-ci.com/user/jwt

### CODE REVIEW

**Comment by Princu7** [comment]
@aayusharora @geekyd @niranjan94 Please guide. I don't really know why the Travis is still failing. It is not able to export the environment variables set up. Sauce Connect should work on external PRs if the API key is encrypted with the JWT addon. I did just that in this Pull Request but it is still not able to do the job. At first, it seemed it was not able to possible Sauce Cloud on PRs but it seems to be doable.

Here are the relavant links:
https://github.com/travis-ci/travis-ci/issues/6569
https://docs.travis-ci.com/user/jwt
https://docs.travis-ci.com/user/sauce-connect/

Could it be that we have the environment variables added in the PR by making changes in the travis.yml are not availabe immediately? Do we have to force push and then see the changes. Please guide. Thanks!!

**Comment by geekyd** [comment]
@Princu7 Please add the username in the env section. check https://docs.travis-ci.com/user/jwt/#List-of-Third-Party-Services-Integrated-with-the-JWT-Addon

**Comment by Princu7** [comment]
@geekyd Thanks. I guess it should not make much difference. I actually just tried what was written on the official guide. 
https://docs.travis-ci.com/user/sauce-connect/
Seems like we have to force push and then see it anything happens since in the Travis logs, it also says something like this. `Encrypted environment variables have been removed for security reasons.` Just waiting for confirmation. :face_with_head_bandage:

**Comment by Princu7** [comment]
@mariobehling @aayusharora 
So, after reading up a lot on the matter and trying out many things many times ( I created an branch named `TravisTest`  on this repository for testing this. Will delete that branch after this is merged ), the Travis is finally green and we are able to connect to the Sauce Cloud on Pull request builds for running Selenium tests. It should be fine now. Please merge this. Thanks!!

**Pull request merged**
