### PR TITLE
Sponsor section

### PR DESCRIPTION
**Pull request by aayusharora**
Issue Related #571 
Please Merge the PR #600 before this.
**Top layout before**

**Mid Layout after**

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks. Please solve the relevant hound-ci issues. Thank you.

**Comment by aayusharora** [comment]
@mariobehling Try to solve maximum Houndci issues, Please merge after merging #600

**Comment by championswimmer** [comment]
@aayusharora  this has a conflict

**Comment by aayusharora** [comment]
@championswimmer Solved merge Conflicts !!

**Pull request merged**
