### PR TITLE
Adds feature to view slides of the session

### LINKED ISSUE #1809: Add "Slides" button to session and adapt design accordingly
While "Slides" are added to the eventyay system and supported in the API, there is no link for the slides yet.

Please add a slides button as shown in the screenshot below and change the display of the star button as well accordingly.

screenshot from 2018-04-03 17-09-02

### PR DESCRIPTION
**Pull request by agbilotia1998**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.

#### Short description of what this resolves:
Adds option to view slides of the session

Fixes #1809

### CODE REVIEW

**Comment by mariobehling** [comment]
Let's follow best practices more closely as we progress. Please provide screenshots and test links.

**Comment by agbilotia1998** [comment]
@mariobehling though slides URL are not available for any event, I tested it using dummy data. I am posting here a screenshot of the slideshow with test data - 
screenshot-2018-5-23 mozilla all hands 2017

**Comment by mariobehling** [comment]
Asking again also in this issue.

> Let's follow best practices more closely as we progress. Please provide screenshots and test links.

**Comment by agbilotia1998** [comment]
Test Link: https://agbilotia1998.github.io/Moz-slides/schedule.html

**Comment by geekyd** [comment]
@agbilotia1998 Can we try to use an open source viewer for the slides?

**Comment by agbilotia1998** [comment]
@geekyd I searched for many slide-viewers but there are open source alternatives for pdf slides only, LibreOffice also does not any such iframe or embedded object in HTML. Any suggestions from your side?

**Pull request merged**
