### PR TITLE
#1045 : disable radio buttons and email field while app is generating

### LINKED ISSUE #1045: Bugs related to app generator page
**App generator issues**
I invite all to discuss the issues related to the app generator page.

**Generate app button**

- Enabled if email is empty
- Remains disabled if zip is uploaded before entering the email.
- Colour of alert shown if incorrect email is entered should be changed to red.

**Cancel generation**

- When user clicks X while app is generating, the generation process must stop
- Disable all the buttons, radio buttons while app is generating
- Hide logs, status text, progress bar when user cancels

**Other**

- Hide progress bar if the app has been generated.
- Reset app generator if source is changed.
- Increase spacing between buttons.

### PR DESCRIPTION
**Pull request by sumedh123**
Fixes #1045 .

Changes : 
    1) Radio buttons and email input are disabled while generating the app.
    2) Added spaces between four buttons

Opinions @Princu7  @aayusharora  @mariobehling ?

### CODE REVIEW

**Comment by Princu7** [comment]
@sumedh123 Nice work. Looks good. Can you please also provide the screenshot with the updated view of the buttons with spaces between them. It is not visible in the uploaded gif. Thanks!!

**Comment by sumedh123** [comment]
@Princu7 
fossasia

**Comment by Princu7** [comment]
@sumedh123 Thanks for uploading the image of the buttons. In my opinion, they look a bit too much far apart from each other. I kinda like the previous look of the buttons a bit more than this. But, the user experience is different for every person so I might be wrong. Let's take more inputs and then proceed with this look. Hope this is okay. Thanks.
@aayusharora Inputs, please?

**Comment by sumedh123** [comment]
@Princu7  Shall I get those breaking spaces removed? Now I am feeling that the previous view was better.

**Comment by aayusharora** [comment]
@sumedh123 Please make the space less.

**Comment by sumedh123** [comment]
@aayusharora @Princu7

**Pull request merged**
