### PR TITLE
sass files with light and dark theme

### PR DESCRIPTION
**Pull request by aayusharora**
@mariobehling  , @juslee  ,@championswimmer
**How to run this ?**
For now , till the process automates  which will be handled at backend after a parameter light or dark is passed in POST request .
1. Install Ruby 
2. Install SASS
3. Run sass --watch /path/application.scss:/path/schedule.css
 This will create schedule.css inside the path you have given .This will be the default CSS that is same as the current CSS .
4. For creating light theme , go to _themes/_light-theme and run sass --watch _light.scss:schedule.css
This will create a schedule.css with background color light gray .
5. For creating light theme , go to _themes/_dark-theme and run sass --watch _dark.scss:schedule.css
This will create a schedule.css with background color  gray .
 
I will optimize _application.scss in next PR , this can be merged .

### CODE REVIEW

**Comment by aayusharora** [comment]
DARK

**Comment by aayusharora** [comment]
LIGHT

**Comment by championswimmer** [comment]
Any particular reason for all the folder names to have an underscore in the beginning ?

**Comment by aayusharora** [comment]
@championswimmer  Just followed SASS documentation and some SASS developers coding guidelines :)
http://thesassway.com/beginner/how-to-structure-a-sass-project
and a dicussion on sass repository https://github.com/sass/sass/issues/384

**Pull request merged**
