### PR TITLE
Search Box and date UI fix 

### PR DESCRIPTION
**Pull request by aayusharora**
Issue  #864

d1

### CODE REVIEW

**Comment by alexagr** [comment]
Sorry for disappearing for a while :)
IMO putting dates on 3 separate lines grabs too much screen real estate on mobile. We should instead put all 3 dates on the same line. This can be done, for example, by using shorter Day of Week name - e.g. "Mon" instead of "Monday".

**Comment by aayusharora** [comment]
@alexagr Mon has changed to Monday ( full names due to some reason ) earlier, I myself think there is a space wastage in terms of UI/UX. But making them inline on small Viewports make them difficult while clicking i.e that's why col-md-12 layouts are preferred on mobile. 
Please consider all mentioned while concluding the best approach.
Thanks :)

**Comment by alexagr** [comment]
@aayusharora In my opinion if we have to choose between short day names ("Sun" instead of "Sunday") on a single vs multiple lines - the former is a better trade off.

**Comment by mariobehling** [comment]
Actually, it should be still ok, if the full days are written.

Would it also be an option to abbreviate the days only below a certain resolution?

**Comment by aayusharora** [comment]
The day name generation format is handeled by the functions in `moment.js`. According to me, it's not feasible to that. @mariobehling Merge this if looks good.
I will come up with a solution to make it better on small screens.

**Pull request merged**
