### PR TITLE
fix timezone handling for session start/end

### PR DESCRIPTION
**Pull request by alexagr**
Session start/end time is encoded in JSON files in UTC format.
Therefore correct way to transform it into local time is as follows:
    moment.utc(<time from JSON>).localtime().format("HH:mm")

Before my fix, there was some "crazy" code that used hardcoded offset (of 4) that applied "on top" of localtime offset (applied by mistake). Moreover offset was applied to time calculations only - but not to dates... Anyway - now it should be clean and clear.

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks for the pr. Could you resolve the merge conflict, please? Thank you.

**Comment by alexagr** [comment]
sorry - I'm pretty new to the GitHub - how exactly can I resolve the merge conflict?

**Comment by alexagr** [comment]
Merge conflicts resolved.

**Comment by mariobehling** [comment]
Ah, ok that was fast :-)

**Pull request merged**
