### PR TITLE
Add Session Bookmark test on the tracks page

### LINKED ISSUE #1311: Test cases for Selenium testing of the website
These are the proposed test cases which we can check for fixing the regressions:

- [x]  Check whether the name of the event is correct or not
- [x]  Test the links of the navbar. The response code should not be 404.
- [x]  Test the links of the footer. The response code should not be 404.
- [x]  Search is working in both, Starred and All mode. Also, make sure that the search results change instantaneously on adding/removing a character.
- [x]  Tweets are being displayed on the event page.
- [ ]  Subnavbar on rooms and tracks page are working and we get appropriately scrolled down to the relevant section on clicking a link inside it.
- [x]   Clicking and expanding on the session element on all the pages work as expected. The element should collapse and uncollapse predictably.
- [x]  Share button is working.
- [x]  No scrollbars are present on the generated site.
- [x]  The down button which directs users back to the top of the page is working.
- [x]  After expanding the session element, when we click on the speaker picture, we should get redirected to the same speaker on the speaker's page.
- [x]  The track listed on hovering over the speaker's picture should redirect to the same track on the tracks page on clicking.
- [ ]  Check for the color of the font and the color of the tracks and make sure that it is correct.

I will start working on it and open child issues for them. Thanks!!

### PR DESCRIPTION
**Pull request by Princu7**
Partially Fixes the issue #1311

Changes: 
* Add Session Bookmark test on the tracks page

@aayusharora @geekyd @sumedh123 @CosmicCoder96 @anu-007 Please review. Thanks!!

### CODE REVIEW

**Comment by geekyd** [comment]
@Princu7 Where can I check the logs for the tests?

**Comment by Princu7** [comment]
@geekyd Thanks for reviewing. Yes. Here is the link. You can watch the video of the test and get logs and screenshots
https://saucelabs.com/beta/tests/270774d8f571441e839ea03f6597847a/watch#248
Also, the video is little long because a lot is going behind the scenes checking whether the other session elements which are unmarked are getting displayed or not on clicking the `Starred` button.

**Comment by geekyd** [comment]
@Princu7 Can you bookmark one session instead of two it will be easier to review(visually)?

**Comment by Princu7** [comment]
@geekyd Okay. Yes. I agree it is harder to see the area below the bookmarked sessions and visually confirm that there are no other sessions :smile: I initially marked only one but then increased it for more checking multiple bookmarks. But on the backend, it is being extensively checked the display of other sessions and it's coming out to be correct. 
I am currently working to make it easier to review visually also. Thanks!!

**Comment by Princu7** [comment]
@geekyd Sorry for the delay. There were some unexpected errors and it took some time to handle them. I have now kept the number of bookmarked elements same but now, we will automatically scroll down vertically by some pixel and it will be easier to see that there are no other bookmarked sessions on the page. Please check. Thanks
https://saucelabs.com/beta/tests/9f2ff56d92264a249749e11c2139e1a5/watch#251

**Comment by mariobehling** [comment]
@Princu7 @geekyd Thank you!

Let's try to get more people to review PRs in this component.

Cheers.

**Pull request merged**
