### PR TITLE
Enabled dark theme

### LINKED ISSUE #1707: Enable dark theme for this project.
**Actual Behaviour**

Currently dark theme is disabled.

**Expected Behaviour**

Enable the dark theme and open UI issues for it.
**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by agbilotia1998**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.

#### Short description of what this resolves:
Enables dark theme.

#### Changes proposed in this pull request:

- Added dropdown for choosing the theme. 

Fixes #1707 

Link to review-
https://openeveweb.herokuapp.com/

### CODE REVIEW

**Comment by agbilotia1998** [comment]
Okay @geekyd

**Comment by agbilotia1998** [comment]
@geekyd please review.

**Comment by agbilotia1998** [comment]
@geekyd if the changes are fine can I modify the tests because travis is failing for now.

**Comment by geekyd** [comment]
@agbilotia1998 Is the deployment link updated?

**Comment by agbilotia1998** [comment]
I've updated the link @geekyd please check.

**Comment by geekyd** [comment]
@agbilotia1998 Good work in adding functionality for choosing a theme, but the dark mode is not yet at par with the expectations. Get inspiration from how twitter does it on their apps.

**Comment by agbilotia1998** [comment]
@geekyd can we enable this and open UI issues for this theme.

**Comment by geekyd** [comment]
@agbilotia1998 That sound good please create an issue to implement the theme.

**Comment by agbilotia1998** [comment]
Okay @geekyd :)

**Comment by agbilotia1998** [comment]
Should I modify the tests as travis would fail now?

**Comment by geekyd** [comment]
@agbilotia1998 Yes, we must update tests are failing after making the changes.

**Comment by agbilotia1998** [comment]
Updating them 👍

**Comment by agbilotia1998** [comment]
@geekyd done please check!

**Comment by agbilotia1998** [comment]
@geekyd instead of updating the tests I have modified the parameter passed while sample generation.Please check.

**Pull request merged**
