### PR TITLE
Fixing travis error

### LINKED ISSUE #1512: Fix travis for the application
**Actual Behaviour**
The travis build is failing for each PR. Please check https://travis-ci.org/fossasia/open-event-webapp/builds/290453248?utm_source=github_status&utm_medium=notification

**Expected Behaviour**
The travis must pass for each build.

This is a known issue in travis :
```
No output has been received in the last 10m0s,
this potentially indicates a stalled build or something wrong with the build itself.
```

### PR DESCRIPTION
**Pull request by invinciblycool**
Fixes #1512 

Changes:
Added `travis_wait`.
Read more about `travis_wait` [here](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received)

### CODE REVIEW

**Comment by invinciblycool** [comment]
@agbilotia1998 Let's see if 30 minutes does the trick. :smile:

**Comment by agbilotia1998** [comment]
@invinciblycool the travis is still failing can you try adding travis_wait to any script that is to be executed after success instead on istanbul cover_mocha. As istanbul cover_mocha is getting executed and travis  waits for it , we should try waiting for after success script it may be happening that istanbul cover_mocha is taking more time to exit.

**Comment by invinciblycool** [comment]
@agbilotia1998 I guess the error is while running `istanbul cover _mocha` itself, since there is no evidence of the next command being executed by Travis in the logs. Also if you see the logs, `istanbul cover _mocha` exits with a status 137 which is suspicious.

**Comment by agbilotia1998** [comment]
@mariobehling can we close this as there is no progress.

**Comment by geekyd** [comment]
Closing this,
Issue was resolved in #1551

**Pull request closed without merging**
