### PR TITLE
updation of installation on local machine in first step

### PR DESCRIPTION
**Pull request by dexta11**
there is problem with python. npm is able to find python but cant run it, it need permission so type npm install bcrypt

### CODE REVIEW

**Comment by geekyd** [comment]
@dexta11 Thank you for reporting the issue. It is recommended to create an issue before generating a PR.

**Comment by dexta11** [comment]
shall i create one ..or it i s ok ?

**Comment by Princu7** [comment]
@dexta11 Make sure to follow best practises from next time :) Also there are two files. One is the swap file which is generated by editors like gedit or vim. Please remove that file. Thanks!!

**Comment by aayusharora** [comment]
@dexta11 Can you please squash you commits .

**Comment by dexta11** [comment]
@angularboy hey i am sorry after deleting swapfile i have done the commit
and rebase and i did squash for my last two commits, because of that it got
deleted so i am unable to squash it again. As i cant see my commit in git
log. please help me what to do next.

**Pull request merged**
