### PR TITLE
Issue #998: Implements navbar on rooms page

### PR DESCRIPTION
**Pull request by CosmicCoder96**
image

Live preview at : 
http://cosmiccoder96.github.io/open-event-webapp/

### CODE REVIEW

**Comment by Princu7** [comment]
@CosmicCoder96 Good work :+1:

**Comment by aayusharora** [comment]
Hi @CosmicCoder96 I will love to merge this but I will suggest to make a template file of this navbar as it is repeating aon every page same as we have done with navbar.hbs. This will let us do code optimizations and much cleaner code.

**Comment by CosmicCoder96** [comment]
@aayusharora That sounds great. I will begin working on it and try to implement it .

**Comment by CosmicCoder96** [comment]
@aayusharora I have implemented a partial template for the same. Please have a look.

**Comment by geekyd** [comment]
@CosmicCoder96 Great work 👍

**Comment by Princu7** [comment]
Great work. Merging this.

**Comment by CosmicCoder96** [comment]
@princu7 Thankks :)

**Pull request merged**
