### PR TITLE
Fixes calendar view of the schedule

### LINKED ISSUE #1814: Improve download as PDF for calendar view
**Actual Behaviour**
If the PDF is downloaded in calendar mode, the generated PDF only contains the schedule for one date.

**Expected Behaviour**
The downloaded PDF from calendar mode should contain the schedule for the entire event.

### PR DESCRIPTION
**Pull request by agbilotia1998**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Fixes calendar mode view of schedule.

Fixes:  #1816
Preview Link: https://agbilotia1998.github.io/fossasia/schedule.html

This PR fixes #1814 where the calendar view shows the starting date when none of the dates is selected. The proposed changes show calendar for all dates when no date tab is selected.

### CODE REVIEW

**Comment by agbilotia1998** [comment]
@geekyd I will update it as soon as my university end semester exams get complete.

**Comment by agbilotia1998** [comment]
@geekyd I searched for this problem and found that there is a limit on the size of canvas that can be created, that's why blank pdf or png appears when full schedule download is triggered. What approach should we use now?

**Comment by geekyd** [comment]
@agbilotia1998 One possible solution will be to create a downloadable PDF while generating the app itself. What do you think?

**Comment by agbilotia1998** [comment]
Yes this can be a solution, and we can add the generated pdf /png to event directory itself. This would improve the performance also as it is taking much time by the script running on browser to generate the same.

**Comment by geekyd** [comment]
@agbilotia1998 Good we should go ahead with this I think.

**Comment by agbilotia1998** [comment]
Sure, I will start working on this.

**Comment by agbilotia1998** [comment]
@geekyd I have made changes to this PR and will open a separate one for the pdf download issue. Please review this :)

**Comment by geekyd** [comment]
@agbilotia1998 Is the deployment link updated?

**Comment by agbilotia1998** [comment]
@geekyd I updated the test link, gh-pages may need some time to update.

**Pull request merged**
