### PR TITLE
send email after website is generated

### PR DESCRIPTION
**Pull request by championswimmer**
Signed-off-by: Arnav Gupta <championswimmer@gmail.com>

### CODE REVIEW

**Comment by championswimmer** [comment]
addresses issue #509

**Comment by aayusharora** [comment]
@championswimmer can you add some tests here as we are going down in 1.66% coverage with this.

**Comment by championswimmer** [comment]
@aayusharora  
We have gone down a lot in the last week. Will make separate PR for adding more tests. 

Btw here is screenshot of this PR working on my local deployment
screenshot from 2016-08-01 19-48-07

**Comment by aayusharora** [comment]
Ok @championswimmer Sucessfully get the email with Live Preview and zip to download  Merging this thanks :)

**Pull request merged**
