### PR TITLE
Improved UI Speaker page similar to Fossasia16

### PR DESCRIPTION
**Pull request by aayusharora**
@mariobehling @championswimmer Please check if this looks good.
Issue #572

- [x] Design similar to Fossasia16 speaker section.
- [x] Add overlay on images on hover same as Fossasia16.
- [x] Make Popover work along with this design.
- [x] No scrollbar apart from right side browser scrollbar.

Will carry out more changes in next PR.
**Image 1** 

**Image 2**

### CODE REVIEW

**Comment by mariobehling** [comment]
Which issue is this PR related to? Still no description, no screenshot and no adherence to best practices at the end of GSoC. Makes me sad.

**Comment by aayusharora** [comment]
@mariobehling I was just writing this.

**Comment by mariobehling** [comment]
Please solve issue as outlined in issue itself. If you want to implement other features open a dedicated issue. On the speakers page/section we do not need info about tracks and colors.

Please do focus on the issue at hand and let's move on more quickly. I am afraid the project is failing otherwise. Please follow the issue description and outline.

**Comment by mariobehling** [comment]
I merged it to get some progress, but what about the codacy issues and the missing organization name?

**Comment by aayusharora** [comment]
@mariobehling As I mentioned in the description, this is already very long PR. As you suggested me also earlier to make small PR's so that work can be tracked easily. I will be doing them in next PR.

**Comment by mariobehling** [comment]
@aayusharora I think, you are missing the point. It is not about small PRs only. PRs should be one feature = one PR. You are adding things, that you did not mention in the issue and you are committing continuously with a lot of codacy issues. If you do not entirely solve the issue, please mention that in the description, e.g. "Partly solves issue xyz".

**Pull request merged**
