### PR TITLE
Searchbox directive UI

### PR DESCRIPTION
**Pull request by aayusharora**
@juslee  , please merge #211 , Before it.

**Live Version** :http://cobbler-eagle-68005.bitballoon.com/#/speakers

### CODE REVIEW

**Comment by aayusharora** [comment]
@juslee , @championswimmer , Please merge #211 , before it .

**Comment by championswimmer** [comment]
@aayusharora any idea why the session are not displaying ?

**Comment by championswimmer** [comment]
@aayusharora 
I am merging this. Please fix the sessions directive in a separate PR then

**Comment by aayusharora** [comment]
@championswimmer , will fix it

**Pull request merged**
