### PR TITLE
Fixes : #1104 & #1099 adds end time and improves URLs in tracks page

### PR DESCRIPTION
**Pull request by geekyd**
Solves #1104 
- Adds end time to all sessions in rooms, schedule and tracks page

- Improves direct links in tracks page 

@mariobehling @aayusharora @Princu7 Please review. Thanks 
Test server :
https://open-event-web-appp.herokuapp.com/

Screenshots :
screen shot 2017-03-02 at 1 47 40 am

### CODE REVIEW

**Comment by aayusharora** [comment]
@geekyd Resolving #1099 partially. Copy the session link and paste it in browser, it will redirect to a bit incorrect location.

**Comment by geekyd** [comment]
@aayusharora can you specify the page?

**Comment by aayusharora** [comment]
@geekyd Even if you try the schedule page, it will scroll down but a bit above than it should be.

**Comment by geekyd** [comment]
@aayusharora Okay got it, I think the other pages are good for the links.
Please do check them.

**Comment by geekyd** [comment]
@aayusharora I think we should close #1099 as the problem statement of the issue is solved in tracks page.
I suggest that we should make a new issue for the schedule page, do a pr for it.

**Pull request merged**
