### PR TITLE
manifest.webapp + manifest.json + address under map

### PR DESCRIPTION
**Pull request by PohSayKeong**
Node_modules must be installed before the webapp can be hosted on Firefox. 128x128 image icon must be named "icon-128.png" and be placed in the /assets/img directory.

### CODE REVIEW

**Comment by PohSayKeong** [comment]
This is on the issue https://github.com/fossasia/open-event-webapp/issues/80

**Comment by PohSayKeong** [comment]
added manifest.json on the same issue

**Comment by championswimmer** [comment]
One small change needed (sorry for the nitpick), please put a random icon (even a block of white color would do, we just need a placeholder), at `icon/icon.128.png` and change the icon paths accordingly.

**Comment by PohSayKeong** [comment]
Hi, I've changed the icon file to lowres.ico in icons instead.

**Comment by PohSayKeong** [comment]
I don't think .ico files works on the chrome webapp, so I added a .png for that. I have confirmed that both updated versions works

**Comment by PohSayKeong** [comment]
Hi, I've added the address below the map. It's actually my first time working with AngularJS so I might be making a mistake here. However, I've tested it and everything works fine

**Comment by creativepsyco** [comment]
Please fix your commits, there are many commits coming from a merge. there should only be 1 commit per change (PR)

**Comment by PohSayKeong** [comment]
So I'll need to close this request and start and new one and then commit all my work at once?

**Comment by creativepsyco** [comment]
you can force push to the branch where you did your work and it will appear here. See https://yangsu.github.io/pull-request-tutorial/

**Comment by PohSayKeong** [comment]
I think I am doing something wrong here, I will close this and open up a new one

**Comment by PohSayKeong** [comment]
Really sorry for the mess I made here, I missed a step in the tutorial. I have another pull request set up.

**Pull request closed without merging**
