### PR TITLE
Added Selenium Test for checking tweet section on the page

### PR DESCRIPTION
**Pull request by Princu7**
Partially fixes the issue #1311 

**Changes**:
* The added tests check whether the tweet section is present or not.

**Video for Demonstration**
https://saucelabs.com/beta/tests/20dd281c00004f65b89bb053fea96755/watch#280
Not really visible since it is very fast but it is checking for the presence of the tweet section. If it was not there, the test would have failed.

@aayusharora @geekyd @sumedh123 Please review. Thanks :)

### CODE REVIEW

**Comment by Princu7** [comment]
Loklak seems to be down currently. That's why the tests are failing currently.

**Comment by aayusharora** [comment]
Oh, can you please report this to loklak team on their channel @Princu7

**Comment by Princu7** [comment]
@aayusharora Yes. I reported it. The server is up again but again the tweets are not coming in the response to the request made to the API. Loklak stores the tweets of last 30 days. In the past 30 days, there haven't been any direct tweet made by fossasia (There have been many retweets though!). So, It seems that the current API call doesn't support showing up of retweets in the response. I will confirm this on the channel. and follow up. Thanks :)

**Comment by aayusharora** [comment]
https://loklak.org/api/search.json?timezoneOffset=-330&q=query This works perfect @Princu7

**Comment by Princu7** [comment]
@aayusharora Both the queries work perfectly. But the problem is that they are not showing any retweets.
There haven't been any direct tweets from the fossasia twitter account in the last 30 days and only retweets are there. Since we are not able to fetch any retweets, the test is failing.

https://loklak.org/api/search.json?timezoneOffset=-330&q=from:fossasia
I have asked on the loklak channel about this issue. Will post here if get some info on it. Thanks!!

**Comment by aayusharora** [comment]
Can you point me to the opened issue in loklak @Princu7  about the same.

**Comment by Princu7** [comment]
@aayusharora Um. I had asked on the gitter channel since I thought I would receive a faster response there. Please see below
https://gitter.im/loklak/loklak
I will open an issue regarding it too. Thanks :)

**Comment by Princu7** [comment]
@aayusharora Also, this tweet issue is taking some time to solve. We are generating many events right now like Mozilla All Hands 2017, Facebook Developer Conference, OSCON etc besides FOSSASIA Summit. Can we temporarily run the Selenium tests on another sample, say, FBF 2017 instead of the FA Summit? When the tweet issue is fixed, we can change it back to the FA Summit again. What do you suggest? Please guide. Thanks :)

**Comment by Princu7** [comment]
Okay. I received a response from one of the developers of the loklak team and it seems that the retweets are currently not supported in the loklak server yet. Please see this link:-
https://github.com/loklak/loklak_server/issues/100
So what should we do? Changing the sample seem to be the only viable option to me. Please guide. Thanks :)

**Comment by aayusharora** [comment]
I will suggest we should take a suggestion from @mariobehling in this case.

**Comment by mariobehling** [comment]
I don't think including too many external services in the tests is a good idea.

**Comment by Princu7** [comment]
Yes. Makes Sense. @aayusharora So what should we do. I think that instead of checking whether the actual tweets are being fetched or not. I guess it would be better if we just check that the tweet section is present in the site or not. That way, we are not depending on the external services and able to proide a basic test to ensure that the tweet functionality is present. Please guide. Thanks!!

**Comment by arp95** [comment]
is loklak now showing tweets?
because i dont think they show up in any of samples in Open Event sample

**Comment by Princu7** [comment]
@arp95 Loklak only stores the tweet of the last 30 days. Since almost of the Twitter accounts used in the sample have not made any direct tweets in the past month ( there have been some retweets from few accounts though but the loklak server doesn't support them presently), tweets are not showing up on the most of the event page.

**Comment by Princu7** [comment]
@aayusharora This issue has been open for quite some time. Please guide on how to proceed with it. Please see my comment above. Thanks!! :)

**Comment by Princu7** [comment]
I have modified the test to check whether the tweet section is present or not instead of checking whether the test section is present or not. If the tweet section is not present, then it will throw an error.  
@aayusharora @geekyd @sumedh123 @anu-007 Please review. Thanks :)

**Pull request merged**
