### PR TITLE
improve filter system of schedule page

### LINKED ISSUE #1822: Track and Room filters are not working in calendar mode
**Screenshots of the issue**

Screenshot of track filter issue
filtertrack

Screenshot of room filter issue
filterroom

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by AdityaHirapara**
#### Short description of what this resolves:
Fix bugs in the filter system of schedule page. Also, add track and room filter for calendar mode.

#### Changes proposed in this pull request:

1. Add track and room filter for _calendar_ mode in schedule page.

2. Display "no results" message after applying _track or room filter_, if there are no matching results.
**Before change** ( Message is not shown, even there are no matching results )
fosstrackroomfiltnores
**After change**
localtrackroomfiltnores

3. While applying _search filter_ in _calendar_ mode, it will filter data for all dates (As in track mode).
**Before change** ( It is filtering only current date sessions, No change in other dates )
fosscalfoss
**After change**
localcalfoss

4. Fix "no results" message activity.
    - While applying _clear filter_.
**Before change** ("no results" message is shown even after removing filter)
fossclearfiltnores
**After change**
localclearfiltnores

    - While switching between dates.
**Before change** ( "no results" is shown because current date has no matching results, but it remains for other dates too )
fosstracknores
**After change**
localtracknores

Fixes #1822.

Deployment link: https://adityahirapara.github.io/eventSiteWebApp/schedule.html

### CODE REVIEW

**Comment by geekyd** [comment]
@AdityaHirapara Okay, is the deployment link updated, because it is not working in the deployment.

**Comment by AdityaHirapara** [comment]
It is working for me, @geekyd 

comment

**Comment by shubham3211** [comment]
@AdityaHirapara Great work when you are showing no result found message the star for bookmark is coming down which is not looking good , you can display the no result found message in the box in which clear filter is written and display it in red.

**Comment by geekyd** [comment]
@AdityaHirapara Thank you! :)

**Comment by joeytwiddle** [comment]
A bit late perhaps, but I suggest the "No matching results found" results could appear in the results area, instead of resizing the input box.

**Pull request merged**
