### PR TITLE
fix: Reduce overall build time for website generation

### LINKED ISSUE #2394: Configure builder to use esbuild and reduce the overall build time
The generation of site comprises of the following steps:

1. Downloading the assets from ZIP/server. This includes JSON and images/audio/slides
2. Running template engine and generating HTML from the JSON files
3. Copying JS and CSS files and minifying and bundling them

Only the first step is something which should be allowed to be slow. Running the template engine should not take more than a second and copying and minifying the JS and CSS files is not transpiling huge trees of node_modules like in react, vue or ember. It's using traditional JS/jQuery which just needs minification. Thus, it is unacceptable for website generator to take more than 2 seconds except for the downloading part. It is literally just copying files here and there.

Please reduce the time it takes to build a site and use esbuild https://github.com/evanw/esbuild to speed up the process even more

### PR DESCRIPTION
**Pull request by dhruvjain99**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Earlier the html pages were minified multiple times, once using html-minifier and gulp-htmlmin and JS and CSS were minified using slow build and minification tools like uglify and gulp-minify-css. Html minifcation is not required so it removed and esbuild is used for minification.

#### Changes proposed in this pull request:

- Remove HTML minification
- Replace gulp- babel, uglify, and iife with gulp-esbuild plugin to minify JS and css

Fixes #2394

### CODE REVIEW

**Comment by dhruvjain99** [comment]
@iamareebjamal can you please review this PR?

**Comment by iamareebjamal** [comment]
Can you please deploy it on heroku and post a link?

**Comment by dhruvjain99** [comment]
@iamareebjamal I have deployed this PR branch on https://damp-wave-90723.herokuapp.com/

**Comment by iamareebjamal** [comment]
Step `INFO:Compiling the html pages from the templates` is still taking a lot of time

**Comment by iamareebjamal** [comment]
Test on https://api.eventyay.com/v1/events/3689bc98

**Comment by dhruvjain99** [comment]
@iamareebjamal I have found that for template compilation, we just using handlebars npm package which doesn't take much time. Before compilation in the current step itself we are even resizing all the speakers(264x264 size) and sponsors(150x80) images asynchronously using sharp npm package. On my local machine the speed is fast enough to perform the step in not more than 2 seconds. Since I am using free dyno on heroku, the speed is noticeable. Please let me know if we need to try another package for image processing other than sharp which is comparatively fast enough.

**Comment by iamareebjamal** [comment]
Can we please add the message to the logs that it is resizing images currently? Because it is misleading. I tried waiting for a lot of time but the build didn't complete on heroku. Once we add the log and I test the build being completed, I'll merge these changes and then you can explore better options in another PR. 

By any chance we are resizing the images one by one instead of batch resizing 5-10 of them asynchronously? Let's discuss that in another PR, but in this one, please add the log before the actual step of what's happening

**Comment by dhruvjain99** [comment]
@iamareebjamal I have updated the PR by adding log statements and deployed it. Please check.

**Comment by iamareebjamal** [comment]
Stuck on `Resizing speakers images` for me

**Comment by dhruvjain99** [comment]
@iamareebjamal actually my dyno is running out of memory that is why it is stuck at `resizing speaker images`. 

image

Do you have any idea how to resolve it?

**Comment by iamareebjamal** [comment]
Check on the production heroku app. Does it work there?

**Comment by dhruvjain99** [comment]
You are saying to deploy my changes there on the production heroku app?

**Comment by iamareebjamal** [comment]
And
1. It should not consume this much memory. Something is wrong
2. That error doesn't stop the process, I - used to run heavy Java apps on heroku with 750 MB RAM consumption

**Comment by dhruvjain99** [comment]
@iamareebjamal it is due to space occupied by the images downloaded on the dyno. If I upload the zip file of fossasia summit2016, then its working fine. P.S. I recreated my dyno, please use this now https://damp-wave-90723.herokuapp.com/ 
And, I do not have access to fossasia account, I think I won't be able to deploy on production.

**Comment by iamareebjamal** [comment]
No, I meant check on already deployed production app

**Comment by dhruvjain99** [comment]
It is generating fine on production app. Are we also using free dyno for production app?

**Comment by iamareebjamal** [comment]
Yes

**Comment by iamareebjamal** [comment]
For me it is not working on prod as well

**Pull request merged**
